In [103]:
full_text = open('out/MAM-Psalms-tex_noNotes.tex').read().strip()
lines = full_text.split('\n')
len(lines)

2846

In [86]:
lines[50]

'\\pstart[\\subsection*{\\textcolor{red}{פרק ב}}]'

In [87]:
import re
perek_pattern = r'\\pstart\[\\subsection\*\{\\textcolor\{red\}\{פרק\s([א-ת]{1,3})\}\}\]'
for line in lines:
    if re.search(perek_pattern, line):
        # extract perek number
        perek = re.search(perek_pattern, line).group(1)
        print(line, perek)

\pstart[\subsection*{\textcolor{red}{פרק א}}] א
\pstart[\subsection*{\textcolor{red}{פרק ב}}] ב
\pstart[\subsection*{\textcolor{red}{פרק ג}}] ג
\pstart[\subsection*{\textcolor{red}{פרק ד}}] ד
\pstart[\subsection*{\textcolor{red}{פרק ה}}] ה
\pstart[\subsection*{\textcolor{red}{פרק ו}}] ו
\pstart[\subsection*{\textcolor{red}{פרק ז}}] ז
\pstart[\subsection*{\textcolor{red}{פרק ח}}] ח
\pstart[\subsection*{\textcolor{red}{פרק ט}}] ט
\pstart[\subsection*{\textcolor{red}{פרק י}}] י
\pstart[\subsection*{\textcolor{red}{פרק יא}}] יא
\pstart[\subsection*{\textcolor{red}{פרק יב}}] יב
\pstart[\subsection*{\textcolor{red}{פרק יג}}] יג
\pstart[\subsection*{\textcolor{red}{פרק יד}}] יד
\pstart[\subsection*{\textcolor{red}{פרק טו}}] טו
\pstart[\subsection*{\textcolor{red}{פרק טז}}] טז
\pstart[\subsection*{\textcolor{red}{פרק יז}}] יז
\pstart[\subsection*{\textcolor{red}{פרק יח}}] יח
\pstart[\subsection*{\textcolor{red}{פרק יט}}] יט
\pstart[\subsection*{\textcolor{red}{פרק כ}}] כ
\pstart[\subsection*{\textcolor{red}{פרק כא}}] כא
\pstart[\subsection*{\textcolor{red}{פרק כב}}] כב
\pstart[\subsection*{\textcolor{red}{פרק כג}}] כג
\pstart[\subsection*{\textcolor{red}{פרק כד}}] כד
\pstart[\subsection*{\textcolor{red}{פרק כה}}] כה
\pstart[\subsection*{\textcolor{red}{פרק כו}}] כו
\pstart[\subsection*{\textcolor{red}{פרק כז}}] כז
\pstart[\subsection*{\textcolor{red}{פרק כח}}] כח
\pstart[\subsection*{\textcolor{red}{פרק כט}}] כט
\pstart[\subsection*{\textcolor{red}{פרק ל}}] ל
\pstart[\subsection*{\textcolor{red}{פרק לא}}] לא
\pstart[\subsection*{\textcolor{red}{פרק לב}}] לב
\pstart[\subsection*{\textcolor{red}{פרק לג}}] לג
\pstart[\subsection*{\textcolor{red}{פרק לד}}] לד
\pstart[\subsection*{\textcolor{red}{פרק לה}}] לה
\pstart[\subsection*{\textcolor{red}{פרק לו}}] לו
\pstart[\subsection*{\textcolor{red}{פרק לז}}] לז
\pstart[\subsection*{\textcolor{red}{פרק לח}}] לח
\pstart[\subsection*{\textcolor{red}{פרק לט}}] לט
\pstart[\subsection*{\textcolor{red}{פרק מ}}] מ
\pstart[\subsection*{\textcolor{red}{פרק מא}}] מא
\pstart[\subsection*{\textcolor{red}{פרק מב}}] מב
\pstart[\subsection*{\textcolor{red}{פרק מג}}] מג
\pstart[\subsection*{\textcolor{red}{פרק מד}}] מד
\pstart[\subsection*{\textcolor{red}{פרק מה}}] מה
\pstart[\subsection*{\textcolor{red}{פרק מו}}] מו
\pstart[\subsection*{\textcolor{red}{פרק מז}}] מז
\pstart[\subsection*{\textcolor{red}{פרק מח}}] מח
\pstart[\subsection*{\textcolor{red}{פרק מט}}] מט
\pstart[\subsection*{\textcolor{red}{פרק נ}}] נ
\pstart[\subsection*{\textcolor{red}{פרק נא}}] נא
\pstart[\subsection*{\textcolor{red}{פרק נב}}] נב
\pstart[\subsection*{\textcolor{red}{פרק נג}}] נג
\pstart[\subsection*{\textcolor{red}{פרק נד}}] נד
\pstart[\subsection*{\textcolor{red}{פרק נה}}] נה
\pstart[\subsection*{\textcolor{red}{פרק נו}}] נו
\pstart[\subsection*{\textcolor{red}{פרק נז}}] נז
\pstart[\subsection*{\textcolor{red}{פרק נח}}] נח
\pstart[\subsection*{\textcolor{red}{פרק נט}}] נט
\pstart[\subsection*{\textcolor{red}{פרק ס}}] ס
\pstart[\subsection*{\textcolor{red}{פרק סא}}] סא
\pstart[\subsection*{\textcolor{red}{פרק סב}}] סב
\pstart[\subsection*{\textcolor{red}{פרק סג}}] סג
\pstart[\subsection*{\textcolor{red}{פרק סד}}] סד
\pstart[\subsection*{\textcolor{red}{פרק סה}}] סה
\pstart[\subsection*{\textcolor{red}{פרק סו}}] סו
\pstart[\subsection*{\textcolor{red}{פרק סז}}] סז
\pstart[\subsection*{\textcolor{red}{פרק סח}}] סח
\pstart[\subsection*{\textcolor{red}{פרק סט}}] סט
\pstart[\subsection*{\textcolor{red}{פרק ע}}] ע
\pstart[\subsection*{\textcolor{red}{פרק עא}}] עא
\pstart[\subsection*{\textcolor{red}{פרק עב}}] עב
\pstart[\subsection*{\textcolor{red}{פרק עג}}] עג
\pstart[\subsection*{\textcolor{red}{פרק עד}}] עד
\pstart[\subsection*{\textcolor{red}{פרק עה}}] עה
\pstart[\subsection*{\textcolor{red}{פרק עו}}] עו
\pstart[\subsection*{\textcolor{red}{פרק עז}}] עז
\pstart[\subsection*{\textcolor{red}{פרק עח}}] עח
\pstart[\subsection*{\textcolor{red}{פרק עט}}] עט
\pstart[\subsection*{\textcolor{red}{פרק פ}}] פ
\pstart[\subsection*{\textcolor{red}{פרק פא}}] פא
\pstart[\subsection*{\textcolor{red}{פרק פב}}] פב
\pstart[\subsection*{\textcolor{red}{פרק פג}}] פג
\pstart[\subsection*{\textcolor{red}{פרק פד}}] פד
\pstart[\subsection*{\textcolor{red}{פרק פה}}] פה
\pstart[\subsection*{\textcolor{red}{פרק פו}}] פו
\pstart[\subsection*{\textcolor{red}{פרק פז}}] פז
\pstart[\subsection*{\textcolor{red}{פרק פח}}] פח
\pstart[\subsection*{\textcolor{red}{פרק פט}}] פט
\pstart[\subsection*{\textcolor{red}{פרק צ}}] צ
\pstart[\subsection*{\textcolor{red}{פרק צא}}] צא
\pstart[\subsection*{\textcolor{red}{פרק צב}}] צב
\pstart[\subsection*{\textcolor{red}{פרק צג}}] צג
\pstart[\subsection*{\textcolor{red}{פרק צד}}] צד
\pstart[\subsection*{\textcolor{red}{פרק צה}}] צה
\pstart[\subsection*{\textcolor{red}{פרק צו}}] צו
\pstart[\subsection*{\textcolor{red}{פרק צז}}] צז
\pstart[\subsection*{\textcolor{red}{פרק צח}}] צח
\pstart[\subsection*{\textcolor{red}{פרק צט}}] צט
\pstart[\subsection*{\textcolor{red}{פרק ק}}] ק
\pstart[\subsection*{\textcolor{red}{פרק קא}}] קא
\pstart[\subsection*{\textcolor{red}{פרק קב}}] קב
\pstart[\subsection*{\textcolor{red}{פרק קג}}] קג
\pstart[\subsection*{\textcolor{red}{פרק קד}}] קד
\pstart[\subsection*{\textcolor{red}{פרק קה}}] קה
\pstart[\subsection*{\textcolor{red}{פרק קו}}] קו
\pstart[\subsection*{\textcolor{red}{פרק קז}}] קז
\pstart[\subsection*{\textcolor{red}{פרק קח}}] קח
\pstart[\subsection*{\textcolor{red}{פרק קט}}] קט
\pstart[\subsection*{\textcolor{red}{פרק קי}}] קי
\pstart[\subsection*{\textcolor{red}{פרק קיא}}] קיא
\pstart[\subsection*{\textcolor{red}{פרק קיב}}] קיב
\pstart[\subsection*{\textcolor{red}{פרק קיג}}] קיג
\pstart[\subsection*{\textcolor{red}{פרק קיד}}] קיד
\pstart[\subsection*{\textcolor{red}{פרק קטו}}] קטו
\pstart[\subsection*{\textcolor{red}{פרק קטז}}] קטז
\pstart[\subsection*{\textcolor{red}{פרק קיז}}] קיז
\pstart[\subsection*{\textcolor{red}{פרק קיח}}] קיח
\pstart[\subsection*{\textcolor{red}{פרק קיט}}] קיט
\pstart[\subsection*{\textcolor{red}{פרק קכ}}] קכ
\pstart[\subsection*{\textcolor{red}{פרק קכא}}] קכא
\pstart[\subsection*{\textcolor{red}{פרק קכב}}] קכב
\pstart[\subsection*{\textcolor{red}{פרק קכג}}] קכג
\pstart[\subsection*{\textcolor{red}{פרק קכד}}] קכד
\pstart[\subsection*{\textcolor{red}{פרק קכה}}] קכה
\pstart[\subsection*{\textcolor{red}{פרק קכו}}] קכו
\pstart[\subsection*{\textcolor{red}{פרק קכז}}] קכז
\pstart[\subsection*{\textcolor{red}{פרק קכח}}] קכח
\pstart[\subsection*{\textcolor{red}{פרק קכט}}] קכט
\pstart[\subsection*{\textcolor{red}{פרק קל}}] קל
\pstart[\subsection*{\textcolor{red}{פרק קלא}}] קלא
\pstart[\subsection*{\textcolor{red}{פרק קלב}}] קלב
\pstart[\subsection*{\textcolor{red}{פרק קלג}}] קלג
\pstart[\subsection*{\textcolor{red}{פרק קלד}}] קלד
\pstart[\subsection*{\textcolor{red}{פרק קלה}}] קלה
\pstart[\subsection*{\textcolor{red}{פרק קלו}}] קלו
\pstart[\subsection*{\textcolor{red}{פרק קלז}}] קלז
\pstart[\subsection*{\textcolor{red}{פרק קלח}}] קלח
\pstart[\subsection*{\textcolor{red}{פרק קלט}}] קלט
\pstart[\subsection*{\textcolor{red}{פרק קמ}}] קמ
\pstart[\subsection*{\textcolor{red}{פרק קמא}}] קמא
\pstart[\subsection*{\textcolor{red}{פרק קמב}}] קמב
\pstart[\subsection*{\textcolor{red}{פרק קמג}}] קמג
\pstart[\subsection*{\textcolor{red}{פרק קמד}}] קמד
\pstart[\subsection*{\textcolor{red}{פרק קמה}}] קמה
\pstart[\subsection*{\textcolor{red}{פרק קמו}}] קמו
\pstart[\subsection*{\textcolor{red}{פרק קמז}}] קמז
\pstart[\subsection*{\textcolor{red}{פרק קמח}}] קמח
\pstart[\subsection*{\textcolor{red}{פרק קמט}}] קמט
\pstart[\subsection*{\textcolor{red}{פרק קנ}}] קנ

In [88]:
passuk_pattern = r'\{\\loc\{ ([א-ת]{1,3})\}~\}‏'
for line in lines:
    if re.search(passuk_pattern, line):
        # extract passuk number
        passuk = re.search(passuk_pattern, line).group(1)
        print(line, passuk)

{\loc{ א}~}‏אַ֥שְֽׁרֵי הָאִ֗ישׁ{\hfill}אֲשֶׁ֤ר | לֹ֥א הָלַךְ֮ בַּעֲצַ֢ת רְשָׁ֫עִ֥ים\newline\hspace*{.5em}וּבְדֶ֣רֶךְ חַ֭טָּאִים לֹ֥א עָמָ֑ד{\hfill}וּבְמוֹשַׁ֥ב לֵ֝צִ֗ים לֹ֣א יָשָֽׁב׃\par א
{\loc{ ב}~}‏כִּ֤י אִ֥ם בְּתוֹרַ֥ת יְהֹוָ֗ה חֶ֫פְצ֥וֹ{\hfill}וּֽבְתוֹרָת֥וֹ יֶהְגֶּ֗ה יוֹמָ֥ם וָלָֽיְלָה׃\par ב
{\loc{ ג}~}‏וְֽהָיָ֗ה כְּעֵץ֮ שָׁת֢וּל עַֽל־פַּלְגֵ֫י מָ֥יִם{\hfill}אֲשֶׁ֤ר פִּרְי֨וֹ | יִתֵּ֬ן בְּעִתּ֗וֹ ג
{\loc{ ד}~}‏לֹא־כֵ֥ן הָרְשָׁעִ֑ים{\hfill}כִּ֥י אִם־כַּ֝מֹּ֗ץ אֲֽשֶׁר־תִּדְּפֶ֥נּוּ רֽוּחַ׃\par ד
{\loc{ ה}~}‏עַל־כֵּ֤ן | לֹא־יָקֻ֣מוּ רְ֭שָׁעִים בַּמִּשְׁפָּ֑ט{\hfill}וְ֝חַטָּאִ֗ים בַּעֲדַ֥ת צַדִּיקִֽים׃\par ה
{\loc{ ו}~}‏כִּֽי־יוֹדֵ֣עַ יְ֭הֹוָה דֶּ֣רֶךְ צַדִּיקִ֑ים{\hfill}וְדֶ֖רֶךְ רְשָׁעִ֣ים תֹּאבֵֽד׃\par\pend ו
{\loc{ א}~}‏לָ֭מָּה רָגְשׁ֣וּ גוֹיִ֑ם{\hfill}וּ֝לְאֻמִּ֗ים יֶהְגּוּ־רִֽיק׃\par א
{\loc{ ב}~}‏יִ֥תְיַצְּב֨וּ | מַלְכֵי־אֶ֗רֶץ{\hfill}וְרוֹזְנִ֥ים נֽוֹסְדוּ־יָ֑חַד\newline\hspace*{.5em}עַל־יְ֝הֹוָ֗ה\hspace{1em}וְעַל־מְשִׁיחֽוֹ׃\par ב
{\loc{ ג}~}‏נְֽ֭נַתְּקָה אֶת־מֽוֹסְרוֹתֵ֑ימוֹ{\hfill}וְנַשְׁלִ֖יכָה מִמֶּ֣נּוּ עֲבֹתֵֽימוֹ׃\par ג
{\loc{ ד}~}‏יוֹשֵׁ֣ב בַּשָּׁמַ֣יִם יִשְׂחָ֑ק{\hfill}אֲ֝דֹנָ֗י יִלְעַג־לָֽמוֹ׃\par ד
{\loc{ ה}~}‏אָ֤ז יְדַבֵּ֣ר אֵלֵ֣ימוֹ בְאַפּ֑וֹ{\hfill}וּֽבַחֲרוֹנ֥וֹ יְבַהֲלֵֽמוֹ׃\par ה
{\loc{ ו}~}‏וַ֭אֲנִי נָסַ֣כְתִּי מַלְכִּ֑י{\hfill}עַל־צִ֝יּ֗וֹן הַר־קׇדְשִֽׁי׃\par ו
{\loc{ ז}~}‏אֲסַפְּרָ֗ה\hspace{1em}אֶֽ֫ל חֹ֥ק{\hfill}יְֽהֹוָ֗ה אָמַ֘ר אֵלַ֥י בְּנִ֥י אַ֑תָּה\newline\hspace*{.5em}אֲ֝נִ֗י הַיּ֥וֹם יְלִדְתִּֽיךָ׃\par ז
{\loc{ ח}~}‏שְׁאַ֤ל מִמֶּ֗נִּי וְאֶתְּנָ֣ה ג֭וֹיִם נַחֲלָתֶ֑ךָ{\hfill}וַ֝אֲחֻזָּתְךָ֗ אַפְסֵי־אָֽרֶץ׃\par ח
{\loc{ ט}~}‏תְּ֭רֹעֵם בְּשֵׁ֣בֶט בַּרְזֶ֑ל{\hfill}כִּכְלִ֖י יוֹצֵ֣ר תְּנַפְּצֵֽם׃\par ט
{\loc{ י}~}‏וְ֭עַתָּה מְלָכִ֣ים הַשְׂכִּ֑ילוּ{\hfill}הִ֝וָּסְר֗וּ שֹׁ֣פְטֵי אָֽרֶץ׃\par י
{\loc{ יא}~}‏עִבְד֣וּ אֶת־יְהֹוָ֣ה בְּיִרְאָ֑ה{\hfill}וְ֝גִ֗ילוּ בִּרְעָדָֽה׃\par יא
{\loc{ יב}~}‏נַשְּׁקוּ־בַ֡ר{\hfill}פֶּן־יֶאֱנַ֤ף | וְתֹ֬אבְדוּ דֶ֗רֶךְ{\hfill}כִּֽי־יִבְעַ֣ר כִּמְעַ֣ט אַפּ֑וֹ\newline\hspace*{.5em}אַ֝שְׁרֵ֗י כׇּל־ח֥וֹסֵי בֽוֹ׃\par\pend יב
{\loc{ א}~}‏מִזְמ֥וֹר לְדָוִ֑ד{\hfill}בְּ֝בׇרְח֗וֹ מִפְּנֵ֤י | אַבְשָׁל֬וֹם בְּנֽוֹ׃\par א
{\loc{ ב}~}‏יְ֭הֹוָה מָה־רַבּ֣וּ צָרָ֑י{\hfill}רַ֝בִּ֗ים קָמִ֥ים עָלָֽי׃\par ב
{\loc{ ג}~}‏רַבִּים֮ אֹמְרִ֢ים לְנַ֫פְשִׁ֥י{\hfill}אֵ֤ין יְֽשׁוּעָ֓תָה לּ֬וֹ בֵאלֹהִ֬ים סֶֽלָה׃\par ג
{\loc{ ד}~}‏וְאַתָּ֣ה יְ֭הֹוָה מָגֵ֣ן בַּעֲדִ֑י{\hfill}כְּ֝בוֹדִ֗י וּמֵרִ֥ים רֹאשִֽׁי׃\par ד
{\loc{ ה}~}‏ק֭וֹלִי אֶל־יְהֹוָ֣ה אֶקְרָ֑א{\hfill}וַיַּעֲנֵ֨נִי מֵהַ֖ר קׇדְשׁ֣וֹ סֶֽלָה׃\par ה
{\loc{ ו}~}‏אֲנִ֥י שָׁכַ֗בְתִּי וָאִ֫ישָׁ֥נָה{\hfill}הֱקִיצ֑וֹתִי כִּ֖י יְהֹוָ֣ה יִסְמְכֵֽנִי׃\par ו
{\loc{ ז}~}‏לֹֽא־אִ֭ירָא מֵרִבְב֥וֹת עָ֑ם{\hfill}אֲשֶׁ֥ר סָ֝בִ֗יב שָׁ֣תוּ עָלָֽי׃\par ז
{\loc{ ח}~}‏ק֘וּמָ֤ה יְהֹוָ֨ה | \hspace{1em}הוֹשִׁ֘יעֵ֤נִי אֱלֹהַ֗י{\hfill}כִּֽי־הִכִּ֣יתָ אֶת־כׇּל־אֹיְבַ֣י לֶ֑חִי\newline\hspace*{.5em}שִׁנֵּ֖י רְשָׁעִ֣ים שִׁבַּֽרְתָּ׃\par ח
{\loc{ ט}~}‏לַֽיהֹוָ֥ה הַיְשׁוּעָ֑ה{\hfill}עַֽל־עַמְּךָ֖ בִרְכָתֶ֣ךָ סֶּֽלָה׃\par\pend ט
{\loc{ א}~}‏לַמְנַצֵּ֥חַ בִּנְגִינ֗וֹת מִזְמ֥וֹר לְדָוִֽד׃\par א
{\loc{ ב}~}‏בְּקׇרְאִ֡י עֲנֵ֤נִי | אֱלֹ֘הֵ֤י צִדְקִ֗י{\hfill}בַּ֭צָּר הִרְחַ֣בְתָּ לִּ֑י\newline\hspace*{.5em}חׇ֝נֵּ֗נִי\hspace{1em}וּשְׁמַ֥ע תְּפִלָּתִֽי׃\par ב
{\loc{ ג}~}‏בְּנֵ֥י אִ֡ישׁ{\hfill}עַד־מֶ֬ה כְבוֹדִ֣י לִ֭כְלִמָּה\newline\hspace*{.5em}תֶּאֱהָב֣וּן רִ֑יק{\hfill}תְּבַקְשׁ֖וּ כָזָ֣ב סֶֽלָה׃\par ג
{\loc{ ד}~}‏וּדְע֗וּ כִּֽי־הִפְלָ֣ה יְ֭הֹוָה חָסִ֣יד ל֑וֹ{\hfill}יְהֹוָ֥ה יִ֝שְׁמַ֗ע בְּקׇרְאִ֥י אֵלָֽיו׃\par ד
{\loc{ ה}~}‏רִגְז֗וּ\hspace{1em}וְֽאַל־תֶּ֫חֱטָ֥אוּ{\hfill}אִמְר֣וּ בִ֭לְבַבְכֶם עַֽל־מִשְׁכַּבְכֶ֗ם{\hfill}וְדֹ֣מּוּ סֶֽלָה׃\par ה
{\loc{ ו}~}‏זִבְח֥וּ זִבְחֵי־צֶ֑דֶק{\hfill}וּ֝בִטְח֗וּ אֶל־יְהֹוָֽה׃\par ו
{\loc{ ז}~}‏רַבִּ֥ים אֹמְרִים֮ מִֽי־יַרְאֵ֢נ֫וּ ט֥וֹב{\hfill}נְֽסָה־עָ֭לֵינוּ א֨וֹר פָּנֶ֬יךָ יְהֹוָֽה׃\par ז
{\loc{ ח}~}‏נָתַ֣תָּה שִׂמְחָ֣ה בְלִבִּ֑י{\hfill}מֵעֵ֬ת דְּגָנָ֖ם וְתִירוֹשָׁ֣ם רָֽבּוּ׃\par ח
{\loc{ ט}~}‏בְּשָׁל֣וֹם יַחְדָּו֮\hspace{1em}אֶשְׁכְּבָ֢ה וְאִ֫ישָׁ֥ן{\hfill}כִּֽי־אַתָּ֣ה יְהֹוָ֣ה לְבָדָ֑ד\newline\hspace*{.5em}לָ֝בֶ֗טַח תּֽוֹשִׁיבֵֽנִי׃\par\pend ט
{\loc{ א}~}‏לַמְנַצֵּ֥חַ אֶֽל־הַנְּחִיל֗וֹת{\hfill}מִזְמ֥וֹר לְדָוִֽד׃\par א
{\loc{ ב}~}‏אֲמָרַ֖י הַאֲזִ֥ינָה | יְהֹוָ֗ה{\hfill}בִּ֣ינָה הֲגִיגִֽי׃\par ב
{\loc{ ג}~}‏הַקְשִׁ֤יבָה | לְק֬וֹל שַׁוְעִ֗י{\hfill}מַלְכִּ֥י וֵאלֹהָ֑י{\hfill}כִּֽי־אֵ֝לֶ֗יךָ\hspace{1em}אֶתְפַּלָּֽל׃\par ג
{\loc{ ד}~}‏יְֽהֹוָ֗ה בֹּ֭קֶר תִּשְׁמַ֣ע קוֹלִ֑י{\hfill}בֹּ֥קֶר אֶעֱרׇךְ־לְ֝ךָ֗ וַאֲצַפֶּֽה׃\par ד
{\loc{ ה}~}‏כִּ֤י | לֹ֤א אֵֽל־חָפֵ֘ץ רֶ֥שַׁע | אָ֑תָּה{\hfill}לֹ֖א יְגֻרְךָ֣ רָֽע׃\par ה
{\loc{ ו}~}‏לֹֽא־יִתְיַצְּב֣וּ ה֭וֹלְלִים לְנֶ֣גֶד עֵינֶ֑יךָ{\hfill}שָׂ֝נֵ֗אתָ כׇּל־פֹּ֥עֲלֵי אָֽוֶן׃\par ו
{\loc{ ז}~}‏תְּאַבֵּד֮ דֹּבְרֵ֢י כָ֫זָ֥ב{\hfill}אִישׁ־דָּמִ֥ים וּמִרְמָ֗ה{\hfill}יְתָ֘עֵ֥ב | יְהֹוָֽה׃\par ז
{\loc{ ח}~}‏וַאֲנִ֗י בְּרֹ֣ב חַ֭סְדְּךָ אָב֣וֹא בֵיתֶ֑ךָ{\hfill}אֶשְׁתַּחֲוֶ֥ה אֶל־הֵיכַל־קׇ֝דְשְׁךָ֗ בְּיִרְאָתֶֽךָ׃\par ח
{\loc{ ט}~}‏יְהֹוָ֤ה | \hspace{1em}נְחֵ֬נִי בְצִדְקָתֶ֗ךָ{\hfill}לְמַ֥עַן שׁוֹרְרָ֑י{\hfill}(הושר)\kri{הַיְשַׁ֖ר} לְפָנַ֣י דַּרְכֶּֽךָ׃\par ט
{\loc{ י}~}‏כִּ֤י אֵ֪ין בְּפִ֡יהוּ נְכוֹנָה֮{\hfill}קִרְבָּ֢ם הַ֫וּ֥וֹת\newline\hspace*{.5em}קֶֽבֶר־פָּת֥וּחַ גְּרֹנָ֑ם{\hfill}לְ֝שׁוֹנָ֗ם יַחֲלִיקֽוּן׃\par י
{\loc{ יא}~}‏הַ֥אֲשִׁימֵ֨ם | אֱֽלֹהִ֗ים{\hfill}יִפְּלוּ֮ מִֽמֹּעֲצ֢וֹתֵ֫יהֶ֥ם\newline\hspace*{.5em}בְּרֹ֣ב פִּ֭שְׁעֵיהֶם הַדִּיחֵ֑מוֹ{\hfill}כִּי־מָ֥רוּ בָֽךְ׃\par יא
{\loc{ יב}~}‏וְיִשְׂמְח֨וּ כׇל־ח֪וֹסֵי בָ֡ךְ{\hfill}לְעוֹלָ֣ם יְ֭רַנֵּנוּ\newline\hspace*{.5em}וְתָסֵ֣ךְ עָלֵ֑ימוֹ{\hfill}וְֽיַעְלְצ֥וּ בְ֝ךָ֗ אֹהֲבֵ֥י שְׁמֶֽךָ׃\par יב
{\loc{ יג}~}‏כִּֽי־אַתָּה֮ תְּבָרֵ֢ךְ צַ֫דִּ֥יק{\hfill}יְהֹוָ֑ה{\hfill}כַּ֝צִּנָּ֗ה\hspace{1em}רָצ֥וֹן תַּעְטְרֶֽנּוּ׃\par\pend יג
{\loc{ א}~}‏לַמְנַצֵּ֣חַ בִּ֭נְגִינוֹת עַֽל־הַשְּׁמִינִ֗ית{\hfill}מִזְמ֥וֹר לְדָוִֽד׃\par א
{\loc{ ב}~}‏יְֽהֹוָ֗ה אַל־בְּאַפְּךָ֥ תוֹכִיחֵ֑נִי{\hfill}וְֽאַל־בַּחֲמָתְךָ֥ תְיַסְּרֵֽנִי׃\par ב
{\loc{ ג}~}‏חׇנֵּ֥נִי יְהֹוָה֮{\hfill}כִּ֤י אֻמְלַ֫ל אָ֥נִי\newline\hspace*{.5em}רְפָאֵ֥נִי יְהֹוָ֑ה{\hfill}כִּ֖י נִבְהֲל֣וּ עֲצָמָֽי׃\par ג
{\loc{ ד}~}‏וְ֭נַפְשִׁי נִבְהֲלָ֣ה מְאֹ֑ד{\hfill}(ואת)\kri{וְאַתָּ֥ה} יְ֝הֹוָ֗ה עַד־מָתָֽי׃\par ד
{\loc{ ה}~}‏שׁוּבָ֣ה יְ֭הֹוָה חַלְּצָ֣ה נַפְשִׁ֑י{\hfill}ה֝וֹשִׁיעֵ֗נִי לְמַ֣עַן חַסְדֶּֽךָ׃\par ה
{\loc{ ו}~}‏כִּ֤י אֵ֣ין בַּמָּ֣וֶת זִכְרֶ֑ךָ{\hfill}בִּ֝שְׁא֗וֹל מִ֣י יֽוֹדֶה־לָּֽךְ׃\par ו
{\loc{ ז}~}‏יָגַ֤עְתִּי | בְּֽאַנְחָתִ֗י{\hfill}אַשְׂחֶ֣ה בְכׇל־לַ֭יְלָה מִטָּתִ֑י\newline\hspace*{.5em}בְּ֝דִמְעָתִ֗י\hspace{1em}עַרְשִׂ֥י אַמְסֶֽה׃\par ז
{\loc{ ח}~}‏עָשְׁשָׁ֣ה מִכַּ֣עַס עֵינִ֑י{\hfill}עָ֝תְקָ֗ה בְּכׇל־צוֹרְרָֽי׃\par ח
{\loc{ ט}~}‏ס֣וּרוּ מִ֭מֶּנִּי כׇּל־פֹּ֣עֲלֵי אָ֑וֶן{\hfill}כִּֽי־שָׁמַ֥ע יְ֝הֹוָ֗ה ק֣וֹל בִּכְיִֽי׃\par ט
{\loc{ י}~}‏שָׁמַ֣ע יְ֭הֹוָה תְּחִנָּתִ֑י{\hfill}יְ֝הֹוָ֗ה תְּֽפִלָּתִ֥י יִקָּֽח׃\par י
{\loc{ יא}~}‏יֵבֹ֤שׁוּ | וְיִבָּהֲל֣וּ מְ֭אֹד כׇּל־אֹיְבָ֑י{\hfill}יָ֝שֻׁ֗בוּ יֵבֹ֥שׁוּ רָֽגַע׃\par\pend יא
{\loc{ א}~}‏שִׁגָּי֗וֹן לְדָ֫וִ֥ד{\hfill}אֲשֶׁר־שָׁ֥ר לַֽיהֹוָ֑ה\newline\hspace*{.5em}עַל־דִּבְרֵי־כ֝֗וּשׁ בֶּן־יְמִינִֽי׃\par א
{\loc{ ב}~}‏יְהֹוָ֣ה אֱ֭לֹהַי בְּךָ֣ חָסִ֑יתִי{\hfill}הוֹשִׁיעֵ֥נִי מִכׇּל־רֹ֝דְפַ֗י וְהַצִּילֵֽנִי׃\par ב
{\loc{ ג}~}‏פֶּן־יִטְרֹ֣ף כְּאַרְיֵ֣ה נַפְשִׁ֑י{\hfill}פֹּ֝רֵ֗ק וְאֵ֣ין מַצִּֽיל׃\par ג
{\loc{ ד}~}‏יְהֹוָ֣ה אֱ֭לֹהַי אִם־עָשִׂ֣יתִי זֹ֑את{\hfill}אִֽם־יֶשׁ־עָ֥וֶל בְּכַפָּֽי׃\par ד
{\loc{ ה}~}‏אִם־גָּ֭מַלְתִּי שֽׁוֹלְמִ֥י רָ֑ע{\hfill}וָאֲחַלְּצָ֖ה צֽוֹרְרִ֣י רֵיקָֽם׃\par ה
{\loc{ ו}~}‏יִ֥רַדֹּֽף אוֹיֵ֨ב | נַפְשִׁ֡י וְיַשֵּׂ֗ג{\hfill}וְיִרְמֹ֣ס לָאָ֣רֶץ חַיָּ֑י\newline\hspace*{.5em}וּכְבוֹדִ֓י | \hspace{1em}לֶעָפָ֖ר יַשְׁכֵּ֣ן סֶֽלָה׃\par ו
{\loc{ ז}~}‏ק֘וּמָ֤ה יְהֹוָ֨ה | בְּאַפֶּ֗ךָ{\hfill}הִ֭נָּשֵׂא בְּעַבְר֣וֹת צוֹרְרָ֑י\newline\hspace*{.5em}וְע֥וּרָה אֵ֝לַ֗י\hspace{1em}מִשְׁפָּ֥ט צִוִּֽיתָ׃\par ז
{\loc{ ח}~}‏וַעֲדַ֣ת לְ֭אֻמִּים תְּסֽוֹבְבֶ֑ךָּ{\hfill}וְ֝עָלֶ֗יהָ לַמָּר֥וֹם שֽׁוּבָה׃\par ח
{\loc{ ט}~}‏יְהֹוָה֮ יָדִ֢ין עַ֫מִּ֥ים{\hfill}שׇׁפְטֵ֥נִי יְהֹוָ֑ה{\hfill}כְּצִדְקִ֖י וּכְתֻמִּ֣י עָלָֽי׃\par ט
{\loc{ י}~}‏יִגְמׇר־נָ֬א רַ֨ע | רְשָׁעִים֮{\hfill}וּתְכוֹנֵ֢ן צַ֫דִּ֥יק\newline\hspace*{.5em}וּבֹחֵ֣ן לִ֭בּוֹת וּכְלָי֗וֹת{\hfill}אֱלֹהִ֥ים צַדִּֽיק׃\par י
{\loc{ יא}~}‏מָגִנִּ֥י עַל־אֱלֹהִ֑ים{\hfill}מ֝וֹשִׁ֗יעַ יִשְׁרֵי־לֵֽב׃\par יא
{\loc{ יב}~}‏אֱ֭לֹהִים שׁוֹפֵ֣ט צַדִּ֑יק{\hfill}וְ֝אֵ֗ל זֹעֵ֥ם בְּכׇל־יֽוֹם׃\par יב
{\loc{ יג}~}‏אִם־לֹ֣א יָ֭שׁוּב חַרְבּ֣וֹ יִלְט֑וֹשׁ{\hfill}קַשְׁתּ֥וֹ דָ֝רַ֗ךְ וַֽיְכוֹנְנֶֽהָ׃\par יג
{\loc{ יד}~}‏וְ֭לוֹ הֵכִ֣ין כְּלֵי־מָ֑וֶת{\hfill}חִ֝צָּ֗יו לְֽדֹלְקִ֥ים יִפְעָֽל׃\par יד
{\loc{ טו}~}‏הִנֵּ֥ה יְחַבֶּל־אָ֑וֶן{\hfill}וְהָרָ֥ה עָ֝מָ֗ל וְיָ֣לַד שָֽׁקֶר׃\par טו
{\loc{ טז}~}‏בּ֣וֹר כָּ֭רָה וַֽיַּחְפְּרֵ֑הוּ{\hfill}וַ֝יִּפֹּ֗ל בְּשַׁ֣חַת יִפְעָֽל׃\par טז
{\loc{ יז}~}‏יָשׁ֣וּב עֲמָל֣וֹ בְרֹאשׁ֑וֹ{\hfill}וְעַ֥ל קׇ֝דְקֳד֗וֹ חֲמָס֥וֹ יֵרֵֽד׃\par יז
{\loc{ יח}~}‏אוֹדֶ֣ה יְהֹוָ֣ה כְּצִדְק֑וֹ{\hfill}וַ֝אֲזַמְּרָ֗ה שֵֽׁם־יְהֹוָ֥ה עֶלְיֽוֹן׃\par\pend יח
{\loc{ א}~}‏לַמְנַצֵּ֥חַ עַֽל־הַגִּתִּ֗ית{\hfill}מִזְמ֥וֹר לְדָוִֽד׃\par א
{\loc{ ב}~}‏יְהֹוָ֤ה אֲדֹנֵ֗ינוּ{\hfill}מָֽה־אַדִּ֣יר שִׁ֭מְךָ בְּכׇל־הָאָ֑רֶץ\newline\hspace*{.5em}אֲשֶׁ֥ר תְּנָ֥ה ה֝וֹדְךָ֗\hspace{1em}עַל־הַשָּׁמָֽיִם׃\par ב
{\loc{ ג}~}‏מִפִּ֤י עוֹלְלִ֨ים | וְֽיֹנְקִים֮\hspace{1em}יִסַּ֢דְתָּ֫ עֹ֥ז{\hfill}לְמַ֥עַן צוֹרְרֶ֑יךָ{\hfill}לְהַשְׁבִּ֥ית א֝וֹיֵ֗ב וּמִתְנַקֵּֽם׃\par ג
{\loc{ ד}~}‏כִּֽי־אֶרְאֶ֣ה שָׁ֭מֶיךָ מַעֲשֵׂ֣ה אֶצְבְּעֹתֶ֑יךָ{\hfill}יָרֵ֥חַ וְ֝כוֹכָבִ֗ים אֲשֶׁ֣ר כּוֹנָֽנְתָּה׃\par ד
{\loc{ ה}~}‏מָה־אֱנ֥וֹשׁ כִּֽי־תִזְכְּרֶ֑נּוּ{\hfill}וּבֶן־אָ֝דָ֗ם כִּ֣י תִפְקְדֶֽנּוּ׃\par ה
{\loc{ ו}~}‏וַתְּחַסְּרֵ֣הוּ מְּ֭עַט מֵאֱלֹהִ֑ים{\hfill}וְכָב֖וֹד וְהָדָ֣ר תְּעַטְּרֵֽהוּ׃\par ו
{\loc{ ז}~}‏תַּ֭מְשִׁילֵהוּ בְּמַעֲשֵׂ֣י יָדֶ֑יךָ{\hfill}כֹּ֝֗ל שַׁ֣תָּה תַֽחַת־רַגְלָֽיו׃\par ז
{\loc{ ח}~}‏צֹנֶ֣ה וַאֲלָפִ֣ים כֻּלָּ֑ם{\hfill}וְ֝גַ֗ם בַּהֲמ֥וֹת שָׂדָֽי׃\par ח
{\loc{ ט}~}‏צִפּ֣וֹר שָׁ֭מַיִם וּדְגֵ֣י הַיָּ֑ם{\hfill}עֹ֝בֵ֗ר אׇרְח֥וֹת יַמִּֽים׃\par ט
{\loc{ י}~}‏יְהֹוָ֥ה אֲדֹנֵ֑ינוּ{\hfill}מָה־אַדִּ֥יר שִׁ֝מְךָ֗ בְּכׇל־הָאָֽרֶץ׃\par\pend י
{\loc{ א}~}‏לַ֭מְנַצֵּחַ עַל־מ֥וּת לַבֵּ֗ן{\hfill}מִזְמ֥וֹר לְדָוִֽד׃\par א
{\loc{ ב}~}‏אוֹדֶ֣ה יְ֭הֹוָה בְּכׇל־לִבִּ֑י{\hfill}אֲ֝סַפְּרָ֗ה כׇּל־נִפְלְאוֹתֶֽיךָ׃\par ב
{\loc{ ג}~}‏אֶשְׂמְחָ֣ה וְאֶעֶלְצָ֣ה בָ֑ךְ{\hfill}אֲזַמְּרָ֖ה שִׁמְךָ֣ עֶלְיֽוֹן׃\par ג
{\loc{ ד}~}‏בְּשׁוּב־אוֹיְבַ֥י אָח֑וֹר{\hfill}יִכָּשְׁל֥וּ וְ֝יֹאבְד֗וּ מִפָּנֶֽיךָ׃\par ד
{\loc{ ה}~}‏כִּֽי־עָ֭שִׂיתָ מִשְׁפָּטִ֣י וְדִינִ֑י{\hfill}יָשַׁ֥בְתָּ לְ֝כִסֵּ֗א שׁוֹפֵ֥ט צֶֽדֶק׃\par ה
{\loc{ ו}~}‏גָּעַ֣רְתָּ ג֭וֹיִם אִבַּ֣דְתָּ רָשָׁ֑ע{\hfill}שְׁמָ֥ם מָ֝חִ֗יתָ לְעוֹלָ֥ם וָעֶֽד׃\par ו
{\loc{ ז}~}‏הָֽאוֹיֵ֨ב | תַּ֥מּוּ חֳרָב֗וֹת\hspace{1em}לָ֫נֶ֥צַח{\hfill}וְעָרִ֥ים נָתַ֑שְׁתָּ{\hfill}אָבַ֖ד זִכְרָ֣ם הֵֽמָּה׃\par ז
{\loc{ ח}~}‏וַֽ֭יהֹוָה לְעוֹלָ֣ם יֵשֵׁ֑ב{\hfill}כּוֹנֵ֖ן לַמִּשְׁפָּ֣ט כִּסְאֽוֹ׃\par ח
{\loc{ ט}~}‏וְה֗וּא יִשְׁפֹּֽט־תֵּבֵ֥ל בְּצֶ֑דֶק{\hfill}יָדִ֥ין לְ֝אֻמִּ֗ים בְּמֵישָׁרִֽים׃\par ט
{\loc{ י}~}‏וִ֘יהִ֤י יְהֹוָ֣ה מִשְׂגָּ֣ב לַדָּ֑ךְ{\hfill}מִ֝שְׂגָּ֗ב לְעִתּ֥וֹת בַּצָּרָֽה׃\par י
{\loc{ יא}~}‏וְיִבְטְח֣וּ בְ֭ךָ יוֹדְעֵ֣י שְׁמֶ֑ךָ{\hfill}כִּ֤י לֹֽא־עָזַ֖בְתָּ דֹרְשֶׁ֣יךָ יְהֹוָֽה׃\par יא
{\loc{ יב}~}‏זַמְּר֗וּ לַ֭יהֹוָה יֹשֵׁ֣ב צִיּ֑וֹן{\hfill}הַגִּ֥ידוּ בָ֝עַמִּ֗ים עֲלִֽילוֹתָֽיו׃\par יב
{\loc{ יג}~}‏כִּֽי־דֹרֵ֣שׁ דָּ֭מִים אוֹתָ֣ם זָכָ֑ר{\hfill}לֹֽא־שָׁ֝כַ֗ח צַעֲקַ֥ת (עניים)\kri{עֲנָוִֽים}׃\par יג
{\loc{ יד}~}‏חָֽנְנֵ֬נִי יְהֹוָ֗ה{\hfill}רְאֵ֣ה עׇ֭נְיִי מִשֹּׂנְאָ֑י\newline\hspace*{.5em}מְ֝רוֹמְמִ֗י מִשַּׁ֥עֲרֵי מָֽוֶת׃\par יד
{\loc{ טו}~}‏לְמַ֥עַן אֲסַפְּרָ֗ה כׇּֽל־תְּהִלָּ֫תֶ֥יךָ{\hfill}בְּשַׁעֲרֵ֥י בַת־צִיּ֑וֹן{\hfill}אָ֝גִ֗ילָה\hspace{1em}בִּישֽׁוּעָתֶֽךָ׃\par טו
{\loc{ טז}~}‏טָבְע֣וּ ג֭וֹיִם בְּשַׁ֣חַת עָשׂ֑וּ{\hfill}בְּרֶֽשֶׁת־ז֥וּ טָ֝מָ֗נוּ נִלְכְּדָ֥ה רַגְלָֽם׃\par טז
{\loc{ יז}~}‏נ֤וֹדַ֨ע | יְהֹוָה֮\hspace{1em}מִשְׁפָּ֢ט עָ֫שָׂ֥ה{\hfill}בְּפֹ֣עַל כַּ֭פָּיו נוֹקֵ֣שׁ רָשָׁ֑ע{\hfill}הִגָּי֥וֹן סֶֽלָה׃\par יז
{\loc{ יח}~}‏יָשׁ֣וּבוּ רְשָׁעִ֣ים לִשְׁא֑וֹלָה{\hfill}כׇּל־גּ֝וֹיִ֗ם שְׁכֵחֵ֥י אֱלֹהִֽים׃\par יח
{\loc{ יט}~}‏כִּ֤י לֹ֣א לָ֭נֶצַח יִשָּׁכַ֣ח אֶבְי֑וֹן{\hfill}תִּקְוַ֥ת (ענוים)\kri{עֲ֝נִיִּ֗ים} תֹּאבַ֥ד לָעַֽד׃\par יט
{\loc{ כ}~}‏קוּמָ֣ה יְ֭הֹוָה אַל־יָעֹ֣ז אֱנ֑וֹשׁ{\hfill}יִשָּׁפְט֥וּ ג֝וֹיִ֗ם עַל־פָּנֶֽיךָ׃\par כ
{\loc{ כא}~}‏שִׁ֘יתָ֤ה יְהֹוָ֨ה | מוֹרָ֗ה\hspace{1em}לָ֫הֶ֥ם{\hfill}יֵדְע֥וּ גוֹיִ֑ם{\hfill}אֱנ֖וֹשׁ הֵ֣מָּה סֶּֽלָה׃\par\pend כא
{\loc{ א}~}‏לָמָ֣ה יְ֭הֹוָה תַּֽעֲמֹ֣ד בְּרָח֑וֹק{\hfill}תַּ֝עְלִ֗ים לְעִתּ֥וֹת בַּצָּרָֽה׃\par א
{\loc{ ב}~}‏בְּגַאֲוַ֣ת רָ֭שָׁע יִדְלַ֣ק עָנִ֑י{\hfill}יִתָּֽפְשׂ֓וּ | בִּמְזִמּ֖וֹת ז֣וּ חָשָֽׁבוּ׃\par ב
{\loc{ ג}~}‏כִּֽי־הִלֵּ֣ל רָ֭שָׁע עַל־תַּאֲוַ֣ת נַפְשׁ֑וֹ{\hfill}וּבֹצֵ֥עַ בֵּ֝רֵ֗ךְ נִ֘אֵ֥ץ | יְהֹוָֽה׃\par ג
{\loc{ ד}~}‏רָשָׁ֗ע כְּגֹ֣בַהּ אַ֭פּוֹ בַּל־יִדְרֹ֑שׁ{\hfill}אֵ֥ין אֱ֝לֹהִ֗ים כׇּל־מְזִמּוֹתָֽיו׃\par ד
{\loc{ ה}~}‏יָ֘חִ֤ילוּ דְרָכָ֨ובְּכׇל־עֵ֗ת{\hfill}מָר֣וֹם מִ֭שְׁפָּטֶיךָ מִנֶּגְדּ֑וֹ\newline\hspace*{.5em}כׇּל־צ֝וֹרְרָ֗יו\hspace{1em}יָפִ֥יחַ בָּהֶֽם׃\par ה
{\loc{ ו}~}‏אָמַ֣ר בְּ֭לִבּוֹ בַּל־אֶמּ֑וֹט{\hfill}לְדֹ֥ר וָ֝דֹ֗ר אֲשֶׁ֣ר לֹֽא־בְרָֽע׃\par ו
{\loc{ ז}~}‏אָלָ֤ה פִּ֣יהוּ מָ֭לֵא וּמִרְמ֣וֹת וָתֹ֑ךְ{\hfill}תַּ֥חַת לְ֝שׁוֹנ֗וֹ עָמָ֥ל וָאָֽוֶן׃\par ז
{\loc{ ח}~}‏יֵשֵׁ֤ב | בְּמַאְרַ֬ב חֲצֵרִ֗ים{\hfill}בַּֽ֭מִּסְתָּרִים יַהֲרֹ֣ג נָקִ֑י\newline\hspace*{.5em}עֵ֝ינָ֗יו\hspace{1em}לְֽחֵלְכָ֥ה יִצְפֹּֽנוּ׃\par ח
{\loc{ ט}~}‏יֶאֱרֹ֬ב בַּמִּסְתָּ֨ר | כְּאַרְיֵ֬ה בְסֻכֹּ֗ה{\hfill}יֶ֭אֱרֹב לַחֲט֣וֹף עָנִ֑י\newline\hspace*{.5em}יַחְטֹ֥ף עָ֝נִ֗י\hspace{1em}בְּמׇשְׁכ֥וֹ בְרִשְׁתּֽוֹ׃\par ט
{\loc{ י}~}‏(ודכה)\kri{יִדְכֶּ֥ה} יָשֹׁ֑חַ{\hfill}וְנָפַ֥ל בַּ֝עֲצוּמָ֗יו (חלכאים)\kri{חֵ֣ל כָּאִֽים}׃\par י
{\loc{ יא}~}‏אָמַ֣ר בְּ֭לִבּוֹ שָׁ֣כַֽח אֵ֑ל{\hfill}הִסְתִּ֥יר פָּ֝נָ֗יו בַּל־רָאָ֥ה לָנֶֽצַח׃\par יא
{\loc{ יב}~}‏קוּמָ֤ה יְהֹוָ֗ה אֵ֭ל נְשָׂ֣א יָדֶ֑ךָ{\hfill}אַל־תִּשְׁכַּ֥ח (עניים)\kri{עֲנָוִֽים}׃\par יב
{\loc{ יג}~}‏עַל־מֶ֤ה | נִאֵ֖ץ רָשָׁ֥ע | אֱלֹהִ֑ים{\hfill}אָמַ֥ר בְּ֝לִבּ֗וֹ לֹ֣א תִדְרֹֽשׁ׃\par יג
{\loc{ יד}~}‏רָאִ֡תָה כִּי־אַתָּ֤ה | עָ֘מָ֤ל וָכַ֨עַס | תַּבִּיט֮{\hfill}לָתֵ֢ת בְּיָ֫דֶ֥ךָ\newline\hspace*{.5em}עָ֭לֶיךָ יַעֲזֹ֣ב חֵלֵ֑כָה{\hfill}יָ֝ת֗וֹם אַתָּ֤ה | הָיִ֬יתָ עוֹזֵֽר׃\par יד
{\loc{ טו}~}‏שְׁ֭בֹר זְר֣וֹעַ רָשָׁ֑ע{\hfill}וָ֝רָ֗ע תִּֽדְרוֹשׁ־רִשְׁע֥וֹ בַל־תִּמְצָֽא׃\par טו
{\loc{ טז}~}‏יְהֹוָ֣ה מֶ֭לֶךְ עוֹלָ֣ם וָעֶ֑ד{\hfill}אָבְד֥וּ ג֝וֹיִ֗ם מֵאַרְצֽוֹ׃\par טז
{\loc{ יז}~}‏תַּאֲוַ֬ת עֲנָוִ֣ים שָׁמַ֣עְתָּ יְהֹוָ֑ה{\hfill}תָּכִ֥ין לִ֝בָּ֗ם תַּקְשִׁ֥יב אׇזְנֶֽךָ׃\par יז
{\loc{ יח}~}‏לִשְׁפֹּ֥ט יָת֗וֹם וָ֫דָ֥ךְ{\hfill}בַּל־יוֹסִ֥יף ע֑וֹד\newline\hspace*{.5em}לַעֲרֹ֥ץ אֱ֝נ֗וֹשׁ מִן־הָאָֽרֶץ׃\par\pend יח
{\loc{ א}~}‏לַמְנַצֵּ֗חַ לְדָ֫וִ֥ד\newline\hspace*{.5em}בַּֽיהֹוָ֨ה | חָסִ֗יתִי{\hfill}אֵ֭יךְ תֹּאמְר֣וּ לְנַפְשִׁ֑י\newline\hspace*{.5em}(נודו)\kri{נ֝֗וּדִי} הַרְכֶ֥ם צִפּֽוֹר׃\par א
{\loc{ ב}~}‏כִּ֤י הִנֵּ֪ה הָרְשָׁעִ֡ים יִדְרְכ֬וּן קֶ֗שֶׁת{\hfill}כּוֹנְנ֣וּ חִצָּ֣ם עַל־יֶ֑תֶר\newline\hspace*{.5em}לִיר֥וֹת בְּמוֹ־אֹ֝֗פֶל\hspace{1em}לְיִשְׁרֵי־לֵֽב׃\par ב
{\loc{ ג}~}‏כִּ֣י הַ֭שָּׁתוֹת יֵהָרֵס֑וּן{\hfill}צַ֝דִּ֗יק מַה־פָּעָֽל׃\par ג
{\loc{ ד}~}‏יְהֹוָ֤ה | בְּֽהֵ֘יכַ֤ל קׇדְשׁ֗וֹ{\hfill}יְהֹוָה֮ בַּשָּׁמַ֢יִם כִּ֫סְא֥וֹ\newline\hspace*{.5em}עֵינָ֥יו יֶחֱז֑וּ\newline\hspace*{.5em}עַפְעַפָּ֥יו יִ֝בְחֲנ֗וּ בְּנֵ֣י אָדָֽם׃\par ד
{\loc{ ה}~}‏יְהֹוָה֮ צַדִּ֢יק יִ֫בְחָ֥ן{\hfill}וְ֭רָשָׁע וְאֹהֵ֣ב חָמָ֑ס{\hfill}שָֽׂנְאָ֥ה נַפְשֽׁוֹ׃\par ה
{\loc{ ו}~}‏יַמְטֵ֥ר עַל־רְשָׁעִ֗ים פַּ֫חִ֥ים{\hfill}אֵ֣שׁ וְ֭גׇפְרִית וְר֥וּחַ זִלְעָפ֗וֹת{\hfill}מְנָ֣ת כּוֹסָֽם׃\par ו
{\loc{ ז}~}‏כִּֽי־צַדִּ֣יק יְ֭הֹוָה צְדָק֣וֹת אָהֵ֑ב{\hfill}יָ֝שָׁ֗ר יֶחֱז֥וּ פָנֵֽימוֹ׃\par\pend ז
{\loc{ א}~}‏לַמְנַצֵּ֥חַ עַֽל־הַשְּׁמִינִ֗ית{\hfill}מִזְמ֥וֹר לְדָוִֽד׃\par א
{\loc{ ב}~}‏הוֹשִׁ֣יעָה יְ֭הֹוָה כִּֽי־גָמַ֣ר חָסִ֑יד{\hfill}כִּי־פַ֥סּוּ אֱ֝מוּנִ֗ים מִבְּנֵ֥י אָדָֽם׃\par ב
{\loc{ ג}~}‏שָׁ֤וְא | יְֽדַבְּרוּ֮ אִ֤ישׁ אֶת־רֵ֫עֵ֥הוּ{\hfill}שְׂפַ֥ת חֲלָק֑וֹת{\hfill}בְּלֵ֖ב וָלֵ֣ב יְדַבֵּֽרוּ׃\par ג
{\loc{ ד}~}‏יַכְרֵ֣ת יְ֭הֹוָה כׇּל־שִׂפְתֵ֣י חֲלָק֑וֹת{\hfill}לָ֝שׁ֗וֹן מְדַבֶּ֥רֶת גְּדֹלֽוֹת׃\par ד
{\loc{ ה}~}‏אֲשֶׁ֤ר אָמְר֨וּ | לִלְשֹׁנֵ֣נוּ נַ֭גְבִּיר{\hfill}שְׂפָתֵ֣ינוּ אִתָּ֑נוּ{\hfill}מִ֖י אָד֣וֹן לָֽנוּ׃\par ה
{\loc{ ו}~}‏מִשֹּׁ֥ד עֲנִיִּים֮\hspace{1em}מֵאֶנְקַ֢ת אֶבְי֫וֹנִ֥ים{\hfill}עַתָּ֣ה אָ֭קוּם יֹאמַ֣ר יְהֹוָ֑ה\newline\hspace*{.5em}אָשִׁ֥ית בְּ֝יֵ֗שַׁע יָפִ֥יחַֽ לֽוֹ׃\par ו
{\loc{ ז}~}‏אִ֥מְר֣וֹת יְהֹוָה֮\hspace{1em}אֲמָר֢וֹת טְהֹ֫ר֥וֹת{\hfill}כֶּ֣סֶף צָ֭רוּף בַּעֲלִ֣יל לָאָ֑רֶץ{\hfill}מְ֝זֻקָּ֗ק שִׁבְעָתָֽיִם׃\par ז
{\loc{ ח}~}‏אַתָּֽה־יְהֹוָ֥ה תִּשְׁמְרֵ֑ם{\hfill}תִּצְּרֶ֓נּוּ | מִן־הַדּ֖וֹר ז֣וּ לְעוֹלָֽם׃\par ח
{\loc{ ט}~}‏סָבִ֗יב רְשָׁעִ֥ים יִתְהַלָּכ֑וּן{\hfill}כְּרֻ֥ם זֻ֝לּ֗וּת לִבְנֵ֥י אָדָֽם׃\par\pend ט
{\loc{ א}~}‏לַמְנַצֵּ֗חַ מִזְמ֥וֹר לְדָוִֽד׃\par א
{\loc{ ב}~}‏עַד־אָ֣נָה יְ֭הֹוָה תִּשְׁכָּחֵ֣נִי נֶ֑צַח{\hfill}עַד־אָ֓נָה | תַּסְתִּ֖יר אֶת־פָּנֶ֣יךָ מִמֶּֽנִּי׃\par ב
{\loc{ ג}~}‏עַד־אָ֨נָה אָשִׁ֪ית עֵצ֡וֹת בְּנַפְשִׁ֗י{\hfill}יָג֣וֹן בִּלְבָבִ֣י יוֹמָ֑ם\newline\hspace*{.5em}עַד־אָ֓נָה | \hspace{1em}יָר֖וּם אֹיְבִ֣י עָלָֽי׃\par ג
{\loc{ ד}~}‏הַבִּ֣יטָֽה עֲ֭נֵנִי יְהֹוָ֣ה אֱלֹהָ֑י{\hfill}הָאִ֥ירָה עֵ֝ינַ֗י פֶּן־אִישַׁ֥ן הַמָּֽוֶת׃\par ד
{\loc{ ה}~}‏פֶּן־יֹאמַ֣ר אֹיְבִ֣י יְכׇלְתִּ֑יו{\hfill}צָרַ֥י יָ֝גִ֗ילוּ כִּ֣י אֶמּֽוֹט׃\par ה
{\loc{ ו}~}‏וַאֲנִ֤י | בְּחַסְדְּךָ֣ בָטַחְתִּי֮{\hfill}יָ֤גֵ֥ל לִבִּ֗י בִּֽישׁוּעָ֫תֶ֥ךָ\newline\hspace*{.5em}אָשִׁ֥ירָה לַֽיהֹוָ֑ה\newline\hspace*{.5em}כִּ֖י גָמַ֣ל עָלָֽי׃\par\pend ו
{\loc{ א}~}‏לַמְנַצֵּ֗חַ לְדָ֫וִ֥ד\newline\hspace*{.5em}אָ֘מַ֤ר נָבָ֣ל בְּ֭לִבּוֹ\hspace{1em}אֵ֣ין אֱלֹהִ֑ים{\hfill}הִֽשְׁחִ֗יתוּ הִֽתְעִ֥יבוּ עֲלִילָ֗ה\newline\hspace*{.5em}אֵ֣ין עֹֽשֵׂה־טֽוֹב׃\par א
{\loc{ ב}~}‏יְֽהֹוָ֗ה מִשָּׁמַיִם֮\hspace{1em}הִשְׁקִ֢יף עַֽל־בְּנֵי־אָ֫דָ֥ם{\hfill}לִ֭רְאוֹת הֲיֵ֣שׁ מַשְׂכִּ֑יל\newline\hspace*{.5em}דֹּ֝רֵ֗שׁ אֶת־אֱלֹהִֽים׃\par ב
{\loc{ ג}~}‏הַכֹּ֥ל סָר֮ יַחְדָּ֢ו נֶ֫אֱלָ֥חוּ{\hfill}אֵ֤ין עֹֽשֵׂה־ט֑וֹב\newline\hspace*{.5em}אֵ֝֗ין גַּם־אֶחָֽד׃\par ג
{\loc{ ד}~}‏הֲלֹ֥א יָדְעוּ֮ כׇּל־פֹּ֢עֲלֵ֫י אָ֥וֶן{\hfill}אֹכְלֵ֣י עַ֭מִּי אָ֣כְלוּ לֶ֑חֶם\newline\hspace*{.5em}יְ֝הֹוָ֗ה לֹ֣א קָרָֽאוּ׃\par ד
{\loc{ ה}~}‏שָׁ֤ם | פָּ֣חֲדוּ פָ֑חַד{\hfill}כִּֽי־אֱ֝לֹהִ֗ים בְּד֣וֹר צַדִּֽיק׃\par ה
{\loc{ ו}~}‏עֲצַת־עָנִ֥י תָבִ֑ישׁוּ{\hfill}כִּ֖י יְהֹוָ֣ה מַחְסֵֽהוּ׃\par ו
{\loc{ ז}~}‏מִ֥י יִתֵּ֣ן מִצִּיּוֹן֮\hspace{1em}יְשׁוּעַ֢ת יִשְׂרָ֫אֵ֥ל{\hfill}בְּשׁ֣וּב יְ֭הֹוָה שְׁב֣וּת עַמּ֑וֹ{\hfill}יָגֵ֥ל יַ֝עֲקֹ֗ב יִשְׂמַ֥ח יִשְׂרָאֵֽל׃\par\pend ז
{\loc{ א}~}‏מִזְמ֗וֹר לְדָ֫וִ֥ד{\hfill}יְ֭הֹוָה מִי־יָג֣וּר בְּאׇהֳלֶ֑ךָ\newline\hspace*{.5em}מִֽי־יִ֝שְׁכֹּ֗ן\hspace{1em}בְּהַ֣ר קׇדְשֶֽׁךָ׃\par א
{\loc{ ב}~}‏הוֹלֵ֣ךְ תָּ֭מִים וּפֹעֵ֥ל צֶ֑דֶק{\hfill}וְדֹבֵ֥ר אֱ֝מֶ֗ת בִּלְבָבֽוֹ׃\par ב
{\loc{ ג}~}‏לֹֽא־רָגַ֨ל | עַל־לְשֹׁנ֗וֹ{\hfill}לֹא־עָשָׂ֣ה לְרֵעֵ֣הוּ רָעָ֑ה\newline\hspace*{.5em}וְ֝חֶרְפָּ֗ה\hspace{1em}לֹא־נָשָׂ֥א עַל־קְרֹבֽוֹ׃\par ג
{\loc{ ד}~}‏נִבְזֶ֤ה | בְּֽעֵ֘ינָ֤יו נִמְאָ֗ס{\hfill}וְאֶת־יִרְאֵ֣י יְהֹוָ֣ה יְכַבֵּ֑ד\newline\hspace*{.5em}נִשְׁבַּ֥ע לְ֝הָרַ֗ע\hspace{1em}וְלֹ֣א יָמִֽר׃\par ד
{\loc{ ה}~}‏כַּסְפּ֤וֹ | לֹא־נָתַ֣ן בְּנֶשֶׁךְ֮{\hfill}וְשֹׁ֥חַד עַל־נָקִ֗י לֹ֥א לָ֫קָ֥ח\newline\hspace*{.5em}עֹֽשֵׂה־אֵ֑לֶּה\newline\hspace*{.5em}לֹ֖א יִמּ֣וֹט לְעוֹלָֽם׃\par\pend ה
{\loc{ א}~}‏מִכְתָּ֥ם לְדָוִ֑ד\newline\hspace*{.5em}שׇֽׁמְרֵ֥נִי אֵ֝֗ל{\hfill}כִּֽי־חָסִ֥יתִי בָֽךְ׃\par א
{\loc{ ב}~}‏אָמַ֣רְתְּ לַֽ֭יהֹוָה אֲדֹנָ֣י אָ֑תָּה{\hfill}ט֝וֹבָתִ֗י בַּל־עָלֶֽיךָ׃\par ב
{\loc{ ג}~}‏לִ֭קְדוֹשִׁים אֲשֶׁר־בָּאָ֣רֶץ הֵ֑מָּה{\hfill}וְ֝אַדִּירֵ֗י כׇּל־חֶפְצִי־בָֽם׃\par ג
{\loc{ ד}~}‏יִרְבּ֥וּ עַצְּבוֹתָם֮ אַחֵ֢ר מָ֫הָ֥רוּ{\hfill}בַּל־אַסִּ֣יךְ נִסְכֵּיהֶ֣ם מִדָּ֑ם\newline\hspace*{.5em}וּֽבַל־אֶשָּׂ֥א אֶת־שְׁ֝מוֹתָ֗ם\hspace{1em}עַל־שְׂפָתָֽי׃\par ד
{\loc{ ה}~}‏יְֽהֹוָ֗ה מְנָת־חֶלְקִ֥י וְכוֹסִ֑י{\hfill}אַ֝תָּ֗ה תּוֹמִ֥יךְ גּוֹרָלִֽי׃\par ה
{\loc{ ו}~}‏חֲבָלִ֣ים נָֽפְלוּ־לִ֭י בַּנְּעִמִ֑ים{\hfill}אַף־נַ֝חֲלָ֗ת שָֽׁפְרָ֥ה עָלָֽי׃\par ו
{\loc{ ז}~}‏אֲבָרֵ֗ךְ אֶת־יְ֭הֹוָה אֲשֶׁ֣ר יְעָצָ֑נִי{\hfill}אַף־לֵ֝יל֗וֹת יִסְּר֥וּנִי כִלְיוֹתָֽי׃\par ז
{\loc{ ח}~}‏שִׁוִּ֬יתִי יְהֹוָ֣ה לְנֶגְדִּ֣י תָמִ֑יד{\hfill}כִּ֥י מִֽ֝ימִינִ֗י בַּל־אֶמּֽוֹט׃\par ח
{\loc{ ט}~}‏לָכֵ֤ן | שָׂמַ֣ח לִ֭בִּי וַיָּ֣גֶל כְּבוֹדִ֑י{\hfill}אַף־בְּ֝שָׂרִ֗י יִשְׁכֹּ֥ן לָבֶֽטַח׃\par ט
{\loc{ י}~}‏כִּ֤י | לֹא־תַעֲזֹ֣ב נַפְשִׁ֣י לִשְׁא֑וֹל{\hfill}לֹֽא־תִתֵּ֥ן חֲ֝סִידְךָ֗ לִרְא֥וֹת שָֽׁחַת׃\par י
{\loc{ יא}~}‏תּֽוֹדִיעֵנִי֮\hspace{1em}אֹ֤רַח חַ֫יִּ֥ים{\hfill}שֹׂ֣בַע שְׂ֭מָחוֹת אֶת־פָּנֶ֑יךָ\newline\hspace*{.5em}נְעִמ֖וֹת בִּימִינְךָ֣ נֶֽצַח׃\par\pend יא

In [89]:
print(len(full_text))
perakim = re.split(perek_pattern,full_text)
print(len(perakim))
perakim[2]

275165
301

'\n{\\loc{ א}~}\u200fאַ֥שְֽׁרֵי הָאִ֗ישׁ{\\hfill}אֲשֶׁ֤ר\u2009| לֹ֥א הָלַךְ֮ בַּעֲצַ֢ת רְשָׁ֫עִ֥ים\\newline\\hspace*{.5em}וּבְדֶ֣רֶךְ חַ֭טָּאִים לֹ֥א עָמָ֑ד{\\hfill}וּבְמוֹשַׁ֥ב לֵ֝צִ֗ים לֹ֣א יָשָֽׁב׃\\par\n{\\loc{ ב}~}\u200fכִּ֤י אִ֥ם בְּתוֹרַ֥ת יְהֹוָ֗ה חֶ֫פְצ֥וֹ{\\hfill}וּֽבְתוֹרָת֥וֹ יֶהְגֶּ֗ה יוֹמָ֥ם וָלָֽיְלָה׃\\par\n{\\loc{ ג}~}\u200fוְֽהָיָ֗ה כְּעֵץ֮ שָׁת֢וּל עַֽל־פַּלְגֵ֫י מָ֥יִם{\\hfill}אֲשֶׁ֤ר פִּרְי֨וֹ\u2009| יִתֵּ֬ן בְּעִתּ֗וֹ\n\\newline\\hspace*{.5em}וְעָלֵ֥הוּ לֹֽא־יִבּ֑וֹל{\\hfill}וְכֹ֖ל אֲשֶׁר־יַעֲשֶׂ֣ה יַצְלִֽיחַ׃\\par\n{\\loc{ ד}~}\u200fלֹא־כֵ֥ן הָרְשָׁעִ֑ים{\\hfill}כִּ֥י אִם־כַּ֝מֹּ֗ץ אֲֽשֶׁר־תִּדְּפֶ֥נּוּ רֽוּחַ׃\\par\n{\\loc{ ה}~}\u200fעַל־כֵּ֤ן\u2009| לֹא־יָקֻ֣מוּ רְ֭שָׁעִים בַּמִּשְׁפָּ֑ט{\\hfill}וְ֝חַטָּאִ֗ים בַּעֲדַ֥ת צַדִּיקִֽים׃\\par\n{\\loc{ ו}~}\u200fכִּֽי־יוֹדֵ֣עַ יְ֭הֹוָה דֶּ֣רֶךְ צַדִּיקִ֑ים{\\hfill}וְדֶ֖רֶךְ רְשָׁעִ֣ים תֹּאבֵֽד׃\\par\\pend\n'

In [90]:
import pandas as pd
space_table = []
newline= '\\newline\\hspace*{.5em}'
space = '{\\hfill}'
s_space = '\\hspace{1em}'
# \pstart[\subsection*{\textcolor{red}{פרק א}}]
perek_pattern = r'\\pstart\[\\subsection\*\{\\textcolor\{red\}\{פרק\s([א-ת]{1,3})\}\}\]'
passuk_pattern = r'\{\\loc\{ ([א-ת]{1,3})\}~\}‏'
current_perek = None
current_passuk = None
perakim = full_text.split(perek_pattern)
for line in lines:
    fill_count = line.count('{\\hfill}')
    line_count = line.count('\\newline\\hspace*{.5em}')
    s_space_count = line.count('\\hspace{1em}')
    perek_match = re.search(perek_pattern, line)
    passuk_match = re.search(passuk_pattern, line)
    if perek_match:
        current_perek = perek_match.group(1)
        current_passuk = None
        # print(perek)
    if passuk_match:
        current_passuk = passuk_match.group(1)
        # print(passuk)
    if current_perek==None or current_passuk==None or line=="" or line=="\\par" or line=="\\ledpb":
        continue
    space_table.append((fill_count, line_count, s_space_count, current_perek+":"+current_passuk))
space_table_df = pd.DataFrame(space_table, columns=['fill_count', 'line_count', 's_space_count',"loc"])
space_table_df['sum']= space_table_df.fill_count + space_table_df.line_count+space_table_df.s_space_count
space_table_df

      fill_count  line_count  s_space_count   loc  sum
0              2           1              0   א:א    3
1              1           0              0   א:ב    1
2              1           0              0   א:ג    1
3              1           1              0   א:ג    2
4              1           0              0   א:ד    1
...          ...         ...            ...   ...  ...
2525           1           0              0  קנ:ד    1
2526           1           0              0  קנ:ה    1
2527           1           0              0  קנ:ו    1
2528           0           0              0  קנ:ו    0
2529           0           0              0  קנ:ו    0

[2530 rows x 5 columns]

'\\\\pstart\\[\\\\subsection\\*\\{\\\\textcolor\\{red\\}\\{פרק\\s([א-ת]{1,3})\\}\\}\\]'

In [120]:
perakim = re.split(perek_pattern,full_text)[1:]
text_dict = {}
for pi in range(len(perakim))[::2]:
    perek = perakim[pi]
    pesukim = re.split(passuk_pattern,perakim[pi+1])[1:]
    # print(perek, "~~",len(pesukim)/2)
    for vi in range(1,len(pesukim))[::2]:
        passuk = pesukim[vi-1]
        v_text = pesukim[vi].replace('{\\hfill}', '\t').replace('\\newline\\hspace*{.5em}', '\n').replace('\\hspace{1em}', '/ ').replace('\\par', '').replace('\\ledpb', '')
        text_dict[perek+":"+passuk] = '\u200F' + v_text

In [111]:
perakim = re.split(perek_pattern,full_text)[1:]
space_table = []
print(len(perakim))
for pi in range(len(perakim))[::2]:
    perek = perakim[pi]
    pesukim = re.split(passuk_pattern,perakim[pi+1])[1:]
    # print(perek, "~~",len(pesukim)/2)
    for vi in range(1,len(pesukim))[::2]:
        passuk = pesukim[vi-1]
        v_text = pesukim[vi]
        fill_count = v_text.count('{\\hfill}')
        line_count = v_text.count('\\newline\\hspace*{.5em}')
        s_space_count = v_text.count('\\hspace{1em}')
        space_table.append((fill_count, line_count, s_space_count, perek+":"+passuk))
space_table_df = pd.DataFrame(space_table, columns=['fill_count', 'line_count', 's_space_count',"loc"])
space_table_df['sum']= space_table_df.fill_count + space_table_df.line_count+space_table_df.s_space_count
space_table_df

300

      fill_count  line_count  s_space_count   loc  sum
0              2           1              0   א:א    3
1              1           0              0   א:ב    1
2              2           1              0   א:ג    3
3              1           0              0   א:ד    1
4              1           0              0   א:ה    1
...          ...         ...            ...   ...  ...
2522           1           0              0  קנ:ב    1
2523           1           0              0  קנ:ג    1
2524           1           0              0  קנ:ד    1
2525           1           0              0  קנ:ה    1
2526           1           0              0  קנ:ו    1

[2527 rows x 5 columns]

In [136]:
rtl_text = text_dict['פד:ג']
print(rtl_text)

‏נִכְסְפָ֬ה וְגַם־כָּֽלְתָ֨ה | נַפְשִׁי֮/ לְחַצְר֢וֹת יְ֫הֹוָ֥ה	לִבִּ֥י וּבְשָׂרִ֑י	יְ֝רַנְּנ֗וּ אֶ֣ל אֵֽל־חָֽי׃

In [112]:
space_table_df[space_table_df['sum'] %2 ==0]

      fill_count  line_count  s_space_count    loc  sum
27             0           0              0    ד:א    0
42             2           0              0    ה:ז    2
60             1           1              0    ז:א    2
68             2           0              0    ז:ט    2
101            1           1              0   ט:יד    2
...          ...         ...            ...    ...  ...
2485           1           1              2  קמז:ח    4
2497           1           1              0  קמז:כ    2
2498           1           1              0  קמח:א    2
2512           1           1              0  קמט:א    2
2521           1           1              0   קנ:א    2

[140 rows x 5 columns]

In [154]:
modfied = []
newline= r'\newline\hspace*{.5em}'
space = r'{\hfill}'
s_space = r'\hspace{1em}'
for line in lines:
    fill_count = line.count('{\\hfill}')
    line_count = line.count('\\newline\\hspace*{.5em}')
    splt = line.split('~}')
    loc,txt = None,None
    if len(splt) > 1:
        loc,txt= splt[0],splt[1]
        l_splt= txt.split(newline)
        if fill_count < line_count and loc !="{\loc{ א}":
            print(line.replace(newline, '\n').replace(space, '/\t').replace('\\par', ''))
            # replace last occurance of newline with space
            mod = newline.join(l_splt[:-1]) + space + l_splt[-1]
            mod = loc + '~}' + mod
            modfied.append(mod)
        elif line_count==0 and fill_count==3:
            s_splt = txt.split(space)
            mod = s_splt[0]+space+s_splt[1]+newline+s_splt[2]+space+s_splt[3]
            mod = loc + '~}' + mod
            modfied.append(mod)
        elif l_splt[-1].count(space) != 1 and l_splt[-1].count(s_space) == 1:
            l_splt[-1] = l_splt[-1].replace(s_space, space)
            mod = newline.join(l_splt)
            mod = loc + '~}' + mod
            modfied.append(mod)
        else:
            modfied.append(line)
    else:
        modfied.append(line)

{\loc{ ד}~}‏יְהֹוָ֤ה | בְּֽהֵ֘יכַ֤ל קׇדְשׁ֗וֹ/	יְהֹוָה֮ בַּשָּׁמַ֢יִם כִּ֫סְא֥וֹ
עֵינָ֥יו יֶחֱז֑וּ
עַפְעַפָּ֥יו יִ֝בְחֲנ֗וּ בְּנֵ֣י אָדָֽם׃
{\loc{ ו}~}‏וַאֲנִ֤י | בְּחַסְדְּךָ֣ בָטַחְתִּי֮/	יָ֤גֵ֥ל לִבִּ֗י בִּֽישׁוּעָ֫תֶ֥ךָ
אָשִׁ֥ירָה לַֽיהֹוָ֑ה
כִּ֖י גָמַ֣ל עָלָֽי׃\pend
{\loc{ ה}~}‏כַּסְפּ֤וֹ | לֹא־נָתַ֣ן בְּנֶשֶׁךְ֮/	וְשֹׁ֥חַד עַל־נָקִ֗י לֹ֥א לָ֫קָ֥ח
עֹֽשֵׂה־אֵ֑לֶּה
לֹ֖א יִמּ֣וֹט לְעוֹלָֽם׃\pend
{\loc{ ט}~}‏ק֤וֹל יְהֹוָ֨ה | יְחוֹלֵ֣ל אַיָּלוֹת֮/	וַֽיֶּחֱשֹׂ֢ף יְעָ֫ר֥וֹת
וּבְהֵיכָל֑וֹ
כֻּ֝לּ֗וֹ אֹמֵ֥ר כָּבֽוֹד׃
{\loc{ י}~}‏מַה־בֶּ֥צַע בְּדָמִי֮/	בְּרִדְתִּ֢י אֶ֫ל שָׁ֥חַת
הֲיוֹדְךָ֥ עָפָ֑ר
הֲיַגִּ֥יד אֲמִתֶּֽךָ׃
{\loc{ ו}~}‏רַבּ֤וֹת עָשִׂ֨יתָ | אַתָּ֤ה | יְהֹוָ֣ה אֱלֹהַי֮/	נִ֥פְלְאֹתֶ֥יךָ וּמַחְשְׁבֹתֶ֗יךָ אֵ֫לֵ֥ינוּ
אֵ֤ין | עֲרֹ֬ךְ אֵלֶ֗יךָ אַגִּ֥ידָה וַאֲדַבֵּ֑רָה
עָ֝צְמ֗וּ מִסַּפֵּֽר׃
{\loc{ ב}~}‏כִּֽי־אַתָּ֤ה | אֱלֹהֵ֣י מָֽעוּזִּי֮/	לָמָ֢ה זְנַ֫חְתָּ֥נִי
לָֽמָּה־קֹדֵ֥ר אֶתְהַלֵּ֗ךְ
בְּלַ֣חַץ אוֹיֵֽב׃
{\loc{ ד}~}‏וְאָב֤וֹאָה | אֶל־מִזְבַּ֬ח אֱלֹהִ֗ים/	אֶל־אֵל֮ שִׂמְחַ֢ת גִּ֫ילִ֥י
וְאוֹדְךָ֥ בְכִנּ֗וֹר
אֱלֹהִ֥ים אֱלֹהָֽי׃
{\loc{ ד}~}‏כִּ֤י לֹ֪א בְחַרְבָּ֡ם יָ֥רְשׁוּ אָ֗רֶץ/	וּזְרוֹעָם֮ לֹא־הוֹשִׁ֢יעָ֫ה לָּ֥מוֹ
כִּֽי־יְמִינְךָ֣ וּ֭זְרוֹעֲךָ וְא֥וֹר פָּנֶ֗יךָ
כִּ֣י רְצִיתָֽם׃
{\loc{ ח}~}‏אָהַ֣בְתָּ צֶּדֶק֮ וַתִּשְׂנָ֫א רֶ֥שַׁע/	עַל־כֵּ֤ן | מְשָׁחֲךָ֡
אֱלֹהִ֣ים אֱ֭לֹהֶיךָ שֶׁ֥מֶן שָׂשׂ֗וֹן
מֵחֲבֵרֶֽךָ׃
{\loc{ י}~}‏נְדִ֘יבֵ֤י עַמִּ֨ים | נֶאֱסָ֗פוּ/	עַם֮ אֱלֹהֵ֢י אַבְרָ֫הָ֥ם
כִּ֣י לֵ֭אלֹהִים מָֽגִנֵּי־אֶ֗רֶץ
מְאֹ֣ד נַֽעֲלָֽה׃\pend
{\loc{ טו}~}‏כַּצֹּ֤אן | לִ֥שְׁא֣וֹל שַׁתּוּ֮\hspace{1em}מָ֤וֶת יִ֫רְעֵ֥ם/	וַיִּרְדּ֘וּ בָ֤ם יְשָׁרִ֨ים | לַבֹּ֗קֶר
(וצירם)\kri{וְ֭צוּרָם} לְבַלּ֥וֹת שְׁא֗וֹל
מִזְּבֻ֥ל לֽוֹ׃
{\loc{ ו}~}‏לְךָ֤ לְבַדְּךָ֨ | חָטָאתִי֮/	וְהָרַ֥ע בְּעֵינֶ֗יךָ עָ֫שִׂ֥יתִי
לְ֭מַעַן תִּצְדַּ֥ק בְּדׇבְרֶ֗ךָ
תִּזְכֶּ֥ה בְשׇׁפְטֶֽךָ׃
{\loc{ יד}~}‏כִּ֤י הִצַּ֪לְתָּ נַפְשִׁ֡י מִמָּוֶת֮/	הֲלֹ֥א רַגְלַ֗י מִ֫דֶּ֥חִי
לְ֭הִֽתְהַלֵּךְ לִפְנֵ֣י אֱלֹהִ֑ים
בְּ֝א֗וֹר הַחַיִּֽים׃\pend
{\loc{ ד}~}‏עַד־אָ֤נָה | תְּה֥וֹתְת֣וּ עַל־אִישׁ֮/	תְּרָצְּח֢וּ כֻ֫לְּכֶ֥ם
כְּקִ֥יר נָט֑וּי
גָּ֝דֵ֗ר הַדְּחוּיָֽה׃
{\loc{ י}~}‏אַ֤ךְ | הֶ֥בֶל בְּנֵֽי־אָדָם֮/	כָּזָ֢ב בְּנֵ֫י אִ֥ישׁ
בְּמֹאזְנַ֥יִם לַעֲל֑וֹת
הֵ֝֗מָּה מֵהֶ֥בֶל יָֽחַד׃
{\loc{ יא}~}‏אַל־תִּבְטְח֣וּ בְעֹשֶׁק֮/	וּבְגָזֵ֢ל אַל־תֶּ֫הְבָּ֥לוּ
חַ֤יִל | כִּֽי־יָנ֑וּב
אַל־תָּשִׁ֥יתוּ לֵֽב׃
{\loc{ יט}~}‏עָ֘לִ֤יתָ לַמָּר֨וֹם | שָׁ֘בִ֤יתָ שֶּׁ֗בִי/	לָקַ֣חְתָּ מַ֭תָּנוֹת בָּאָדָ֑ם
וְאַ֥ף ס֝וֹרְרִ֗ים
לִשְׁכֹּ֤ן | יָ֬הּ אֱלֹהִֽים׃
{\loc{ ז}~}‏אַל־יֵ֘בֹ֤שׁוּ בִ֨י | קֹוֶיךָ֮/	אֲדֹנָ֥י יֱהֹוִ֗ה צְבָ֫א֥וֹת
אַל־יִכָּ֣לְמֽוּ בִ֣י מְבַקְשֶׁ֑יךָ
אֱ֝לֹהֵ֗י יִשְׂרָאֵֽל׃
{\loc{ ב}~}‏אֱלֹהִ֥ים לְהַצִּילֵ֑נִי
יְ֝הֹוָ֗ה\hspace{1em}לְעֶזְרָ֥תִי חֽוּשָׁה׃
{\loc{ כב}~}‏גַּם־אֲנִ֤י | אוֹדְךָ֣ בִכְלִי־נֶבֶל֮/	אֲמִתְּךָ֢ אֱלֹ֫הָ֥י
אֲזַמְּרָ֣ה לְךָ֣ בְכִנּ֑וֹר
קְ֝ד֗וֹשׁ יִשְׂרָאֵֽל׃
{\loc{ יז}~}‏יְהִ֤י שְׁמ֨וֹ לְֽעוֹלָ֗ם/	לִפְנֵי־שֶׁמֶשׁ֮ (ינין)\kri{יִנּ} שְׁ֫מ֥וֹ
וְיִתְבָּ֥רְכוּ ב֑וֹ
כׇּל־גּוֹיִ֥ם יְאַשְּׁרֽוּהוּ׃
{\loc{ ה}~}‏וַיָּ֤קֶם עֵד֨וּת | בְּֽיַעֲקֹ֗ב/	וְתוֹרָה֮ שָׂ֤ם בְּיִשְׂרָ֫אֵ֥ל
אֲשֶׁ֣ר צִ֭וָּה אֶת־אֲבוֹתֵ֑ינוּ
לְ֝הוֹדִיעָ֗ם לִבְנֵיהֶֽם׃
{\loc{ ו}~}‏שְׁפֹ֤ךְ חֲמָתְךָ֗/	אֶֽל־הַגּוֹיִם֮ אֲשֶׁ֢ר לֹא־יְדָ֫ע֥וּךָ
וְעַ֥ל מַמְלָכ֑וֹת
אֲשֶׁ֥ר בְּ֝שִׁמְךָ֗ לֹ֣א קָרָֽאוּ׃
{\loc{ ט}~}‏עׇזְרֵ֤נוּ | אֱלֹ֘הֵ֤י יִשְׁעֵ֗נוּ/	עַֽל־דְּבַ֥ר כְּבֽוֹד־שְׁמֶ֑ךָ
וְהַצִּילֵ֥נוּ וְכַפֵּ֥ר עַל־חַ֝טֹּאתֵ֗ינוּ
לְמַ֣עַן שְׁמֶֽךָ׃
{\loc{ יג}~}‏וַאֲנַ֤חְנוּ עַמְּךָ֨ | וְצֹ֥אן מַרְעִיתֶךָ֮/	נ֤וֹדֶ֥ה לְּךָ֗ לְע֫וֹלָ֥ם
לְד֥וֹר וָדֹ֑ר
נְ֝סַפֵּ֗ר תְּהִלָּתֶֽךָ׃\pend
{\loc{ יג}~}‏לִפְנֵ֤י יְהֹוָ֨ה | כִּ֬י בָ֗א/	כִּ֥י בָא֮ לִשְׁפֹּ֢ט הָ֫אָ֥רֶץ
יִשְׁפֹּֽט־תֵּבֵ֥ל בְּצֶ֑דֶק
וְ֝עַמִּ֗ים בֶּאֱמוּנָתֽוֹ׃\pend
{\loc{ ה}~}‏(מלושני)\kri{מְלׇשְׁנִ֬י} בַסֵּ֨תֶר | רֵעֵהוּ֮/	אוֹת֢וֹ אַ֫צְמִ֥ית
גְּֽבַהּ־עֵ֭ינַיִם וּרְחַ֣ב לֵבָ֑ב
אֹ֝ת֗וֹ לֹ֣א אוּכָֽל׃
{\loc{ ג}~}‏אַל־תַּסְתֵּ֬ר פָּנֶ֨יךָ | מִמֶּנִּי֮/	בְּי֢וֹם צַ֫ר לִ֥י
הַטֵּֽה־אֵלַ֥י אׇזְנֶ֑ךָ
בְּי֥וֹם אֶ֝קְרָ֗א מַהֵ֥ר עֲנֵֽנִי׃
{\loc{ לה}~}‏יִתַּ֤מּוּ חַטָּאִ֨ים | מִן־הָאָ֡רֶץ/	וּרְשָׁעִ֤ים | ע֤וֹד אֵינָ֗ם
בָּרְכִ֣י נַ֭פְשִׁי אֶת־יְהֹוָ֗ה
הַֽלְלוּ־יָֽהּ׃\pend
{\loc{ מז}~}‏הוֹשִׁיעֵ֨נוּ | יְ֘הֹוָ֤ה אֱלֹהֵ֗ינוּ/	וְקַבְּצֵנוּ֮ מִֽן־הַגּ֫וֹיִ֥ם
לְ֭הֹדוֹת לְשֵׁ֣ם קׇדְשֶׁ֑ךָ
לְ֝הִשְׁתַּבֵּ֗חַ בִּתְהִלָּתֶֽךָ׃
{\loc{ מח}~}‏בָּ֤רֽוּךְ יְהֹוָ֨ה אֱלֹהֵ֪י יִשְׂרָאֵ֡ל/	מִן־הָ֤עוֹלָ֨ם | וְעַ֬ד הָעוֹלָ֗ם
וְאָמַ֖ר כׇּל־הָעָ֥ם אָמֵ֗ן
הַֽלְלוּ־יָֽהּ׃\pend
{\loc{ ב}~}‏נָכ֣וֹן לִבִּ֣י אֱלֹהִ֑ים
אָשִׁ֥ירָה וַ֝אֲזַמְּרָ֗ה אַף־כְּבוֹדִֽי׃
{\loc{ ב}~}‏הִנֵּ֨ה כְעֵינֵ֪י עֲבָדִ֡ים אֶל־יַ֤ד אֲֽדוֹנֵיהֶ֗ם/	כְּעֵינֵ֣י שִׁפְחָה֮ אֶל־יַ֢ד גְּבִ֫רְתָּ֥הּ
כֵּ֣ן עֵ֭ינֵינוּ אֶל־יְהֹוָ֣ה אֱלֹהֵ֑ינוּ
עַ֝֗ד שֶׁיְּחׇנֵּֽנוּ׃
{\loc{ ג}~}‏כִּ֤י לֹ֪א יָנ֡וּחַ שֵׁ֤בֶט הָרֶ֗שַׁע/	עַל֮ גּוֹרַ֢ל הַֽצַּדִּ֫יקִ֥ים
לְמַ֡עַן
לֹא־יִשְׁלְח֖וּ הַצַּדִּיקִ֨ים בְּעַוְלָ֬תָה יְדֵיהֶֽם׃
{\loc{ ה}~}‏אַשְׁרֵ֤י הַגֶּ֗בֶר/	אֲשֶׁ֤ר מִלֵּ֥א אֶת־אַשְׁפָּת֗וֹ מֵ֫הֶ֥ם
לֹֽא־יֵבֹ֑שׁוּ
כִּֽי־יְדַבְּר֖וּ אֶת־אוֹיְבִ֣ים בַּשָּֽׁעַר׃\pend
{\loc{ יא}~}‏נִשְׁבַּֽע־יְהֹוָ֨ה | לְדָוִ֡ד אֱמֶת֮/	לֹא־יָשׁ֢וּב מִ֫מֶּ֥נָּה
מִפְּרִ֥י בִטְנְךָ֑
אָ֝שִׁ֗ית לְכִסֵּא־לָֽךְ׃
{\loc{ יב}~}‏אִֽם־יִשְׁמְר֬וּ בָנֶ֨יךָ | בְּרִיתִי֮/	וְעֵדֹתִ֥י ז֗וֹ אֲלַ֫מְּדֵ֥ם
גַּם־בְּנֵיהֶ֥ם עֲדֵי־עַ֑ד
יֵ֝שְׁב֗וּ לְכִסֵּא־לָֽךְ׃
{\loc{ ז}~}‏זְכֹ֤ר יְהֹוָ֨ה | לִבְנֵ֬י אֱד֗וֹם/	אֵת֮ י֤וֹם יְֽר֫וּשָׁללָ֥͏ִםם
הָ֭אֹ֣מְרִים עָ֤רוּ | עָ֑רוּ
עַ֝֗ד הַיְס֥וֹד בָּֽהּ׃
{\loc{ טז}~}‏גׇּלְמִ֤י | רָ֘א֤וּ עֵינֶ֗יךָ/	וְעַֽל־סִפְרְךָ֮ כֻּלָּ֢ם יִכָּ֫תֵ֥בוּ
יָמִ֥ים יֻצָּ֑רוּ
(ולא)\kri{וְל֖וֹ} אֶחָ֣ד בָּהֶֽם׃
{\loc{ ד}~}‏בְּהִתְעַטֵּ֬ף עָלַ֨י | רוּחִ֗י/	וְאַתָּה֮ יָדַ֢עְתָּ נְֽתִיבָ֫תִ֥י
בְּאֹֽרַח־ז֥וּ אֲהַלֵּ֑ךְ
טָמְנ֖וּ פַ֣ח לִֽי׃

In [134]:
s_space = '\hspace{1em}'
for line in modfied:
    l_splt= line.split(newline)
    if len(l_splt) > 1 and l_splt[-2].count(space) > 1 and l_splt[-1].count(space) == 0:
        print(line)

{\loc{ יב}~}‏נַשְּׁקוּ־בַ֡ר{\hfill}פֶּן־יֶאֱנַ֤ף | וְתֹ֬אבְדוּ דֶ֗רֶךְ{\hfill}כִּֽי־יִבְעַ֣ר כִּמְעַ֣ט אַפּ֑וֹ\newline\hspace*{.5em}אַ֝שְׁרֵ֗י כׇּל־ח֥וֹסֵי בֽוֹ׃\par\pend
{\loc{ א}~}‏תְּפִלָּ֗ה לְדָ֫וִ֥ד\newline\hspace*{.5em}שִׁמְעָ֤ה יְהֹוָ֨ה | צֶ֗דֶק{\hfill}הַקְשִׁ֥יבָה רִנָּתִ֗י{\hfill}הַאֲזִ֥ינָה תְפִלָּתִ֑י\newline\hspace*{.5em}בְּ֝לֹ֗א שִׂפְתֵ֥י מִרְמָֽה׃\par
{\loc{ נא}~}‏מַגְדִּל֮ יְשׁוּע֢וֹת מַ֫לְכּ֥וֹ{\hfill}וְעֹ֤שֶׂה חֶ֨סֶד | לִמְשִׁיח֗וֹ{\hfill}לְדָוִ֥ד וּלְזַרְע֗וֹ\newline\hspace*{.5em}עַד־עוֹלָֽם׃\par\pend
{\loc{ ט}~}‏אֶ֤רֶץ רָעָ֨שָׁה | אַף־שָׁמַ֣יִם נָטְפוּ֮{\hfill}מִפְּנֵ֢י אֱלֹ֫הִ֥ים{\hfill}זֶ֥ה סִינַ֑י\newline\hspace*{.5em}מִפְּנֵ֥י אֱ֝לֹהִ֗ים אֱלֹהֵ֥י יִשְׂרָאֵֽל׃\par
{\loc{ לא}~}‏גְּעַ֨ר חַיַּ֪ת קָנֶ֡ה{\hfill}עֲדַ֤ת אַבִּירִ֨ים | בְּעֶגְלֵ֬י עַמִּ֗ים{\hfill}מִתְרַפֵּ֥ס בְּרַצֵּי־כָ֑סֶף\newline\hspace*{.5em}בִּזַּ֥ר עַ֝מִּ֗ים קְרָב֥וֹת יֶחְפָּֽצוּ׃\par
{\loc{ לו}~}‏נ֤וֹרָ֥א אֱלֹהִ֗ים מִֽמִּקְדָּ֫שֶׁ֥יךָ{\hfill}אֵ֤ל יִשְׂרָאֵ֗ל{\hfill}ה֤וּא נֹתֵ֨ן | עֹ֖ז וְתַעֲצֻמ֥וֹת לָעָ֗ם\newline\hspace*{.5em}בָּר֥וּךְ אֱלֹהִֽים׃\par\pend
{\loc{ ד}~}‏לֹ֤א נְכַחֵ֨ד | מִבְּנֵיהֶ֗ם{\hfill}לְד֥וֹר אַחֲר֗וֹן{\hfill}מְֽ֭סַפְּרִים תְּהִלּ֣וֹת יְהֹוָ֑ה\newline\hspace*{.5em}וֶעֱזוּז֥וֹ וְ֝נִפְלְאֹתָ֗יו אֲשֶׁ֣ר עָשָֽׂה׃\par
{\loc{ ח}~}‏וְלֹ֤א יִהְי֨וּ | כַּאֲבוֹתָ֗ם{\hfill}דּוֹר֮ סוֹרֵ֢ר וּמֹ֫רֶ֥ה{\hfill}דּ֭וֹר לֹא־הֵכִ֣ין לִבּ֑וֹ\newline\hspace*{.5em}וְלֹֽא־נֶאֶמְנָ֖ה אֶת־אֵ֣ל רוּחֽוֹ׃\par
{\loc{ ט}~}‏אֶשְׁמְעָ֗ה מַה־יְדַבֵּר֮ הָאֵ֢ל | יְ֫הֹוָ֥ה{\hfill}כִּ֤י | יְדַבֵּ֬ר שָׁל֗וֹם{\hfill}אֶל־עַמּ֥וֹ וְאֶל־חֲסִידָ֑יו\newline\hspace*{.5em}וְאַל־יָשׁ֥וּבוּ לְכִסְלָֽה׃\par
{\loc{ ו}~}‏בַּמֵּתִ֗ים חׇ֫פְשִׁ֥י{\hfill}כְּמ֤וֹ חֲלָלִ֨ים | שֹׁ֥כְבֵי קֶ֗בֶר{\hfill}אֲשֶׁ֤ר לֹ֣א זְכַרְתָּ֣ם ע֑וֹד\newline\hspace*{.5em}וְ֝הֵ֗מָּה מִיָּדְךָ֥ נִגְזָֽרוּ׃\par
{\loc{ א}~}‏מִזְמ֡וֹר{\hfill}שִׁ֤ירוּ לַיהֹוָ֨ה | שִׁ֣יר חָ֭דָשׁ{\hfill}כִּֽי־נִפְלָא֣וֹת עָשָׂ֑ה\newline\hspace*{.5em}הוֹשִׁיעָה־לּ֥וֹ יְ֝מִינ֗וֹ וּזְר֥וֹעַ קׇדְשֽׁוֹ׃\par
{\loc{ כג}~}‏וַיֹּ֗אמֶר לְֽהַשְׁמִ֫ידָ֥ם{\hfill}לוּלֵ֡י מֹ֘שֶׁ֤ה בְחִיר֗וֹ{\hfill}עָמַ֣ד בַּפֶּ֣רֶץ לְפָנָ֑יו\newline\hspace*{.5em}לְהָשִׁ֥יב חֲ֝מָת֗וֹ מֵהַשְׁחִֽית׃\par
{\loc{ ב}~}‏שָׁ֤וְא לָכֶ֨ם מַשְׁכִּ֪ימֵֽי ק֡וּם{\hfill}מְאַחֲרֵי־שֶׁ֗בֶת{\hfill}אֹ֭כְלֵי לֶ֣חֶם הָעֲצָבִ֑ים\newline\hspace*{.5em}כֵּ֤ן יִתֵּ֖ן לִידִיד֣וֹ שֵׁנָֽא׃\par
{\loc{ ו}~}‏תִּדְבַּֽק־לְשׁוֹנִ֨י | לְחִכִּי֮{\hfill}אִם־לֹ֢א אֶ֫זְכְּרֵ֥כִי{\hfill}אִם־לֹ֣א אַ֭עֲלֶה אֶת־יְרוּשׁלַ֑͏ִם\newline\hspace*{.5em}עַ֝֗ל רֹ֣אשׁ שִׂמְחָתִֽי׃\par
{\loc{ ב}~}‏אֶשְׁתַּחֲוֶ֨ה אֶל־הֵיכַ֪ל קׇדְשְׁךָ֡{\hfill}וְא֘וֹדֶ֤ה אֶת־שְׁמֶ֗ךָ{\hfill}עַל־חַסְדְּךָ֥ וְעַל־אֲמִתֶּ֑ךָ\newline\hspace*{.5em}כִּֽי־הִגְדַּ֥לְתָּ עַל־כׇּל־שִׁ֝מְךָ֗ אִמְרָתֶֽךָ׃\par
{\loc{ ד}~}‏אַל־תַּט־לִבִּ֨י\hspace{1em}לְדָבָ֪ר | רָ֡ע{\hfill}לְהִתְע֘וֹלֵ֤ל עֲלִל֨וֹת | בְּרֶ֗שַׁע{\hfill}אֶת־אִישִׁ֥ים פֹּעֲלֵי־אָ֑וֶן\newline\hspace*{.5em}וּבַל־אֶ֝לְחַ֗ם בְּמַנְעַמֵּיהֶֽם׃\par

In [150]:
with open('out/MAM-Psalms-tex_noNotes_mod.tex', 'w') as f:
    f.write('\n'.join(modfied))

In [151]:
modfied_text = open('out/MAM-Psalms-tex_noNotes_mod.tex').read().strip()
perakim = re.split(perek_pattern,modfied_text)[1:]
space_table = []
print(len(perakim))
for pi in range(len(perakim))[::2]:
    perek = perakim[pi]
    pesukim = re.split(passuk_pattern,perakim[pi+1])[1:]
    # print(perek, "~~",len(pesukim)/2)
    for vi in range(1,len(pesukim))[::2]:
        passuk = pesukim[vi-1]
        v_text = pesukim[vi]
        fill_count = v_text.count('{\\hfill}')
        line_count = v_text.count('\\newline\\hspace*{.5em}')
        s_space_count = v_text.count('\\hspace{1em}')
        space_table.append((fill_count, line_count, s_space_count, perek+":"+passuk))
space_table_df = pd.DataFrame(space_table, columns=['fill_count', 'line_count', 's_space_count',"loc"])
space_table_df['sum']= space_table_df.fill_count + space_table_df.line_count+space_table_df.s_space_count
space_table_df['space_sum'] = space_table_df.fill_count + space_table_df.s_space_count
space_table_df[space_table_df['sum'] %2 ==0]

300

      fill_count  line_count  s_space_count    loc  sum  space_sum
27             0           0              0    ד:א    0          0
42             2           0              0    ה:ז    2          2
60             1           1              0    ז:א    2          1
68             2           0              0    ז:ט    2          2
101            1           1              0   ט:יד    2          1
...          ...         ...            ...    ...  ...        ...
2485           2           1              1  קמז:ח    4          3
2497           1           1              0  קמז:כ    2          1
2498           1           1              0  קמח:א    2          1
2512           1           1              0  קמט:א    2          1
2521           1           1              0   קנ:א    2          1

[140 rows x 6 columns]

In [152]:
space_table_df[space_table_df['line_count'] ==0]

      fill_count  line_count  s_space_count   loc  sum  space_sum
1              1           0              0   א:ב    1          1
3              1           0              0   א:ד    1          1
4              1           0              0   א:ה    1          1
5              1           0              0   א:ו    1          1
6              1           0              0   ב:א    1          1
...          ...         ...            ...   ...  ...        ...
2522           1           0              0  קנ:ב    1          1
2523           1           0              0  קנ:ג    1          1
2524           1           0              0  קנ:ד    1          1
2525           1           0              0  קנ:ה    1          1
2526           1           0              0  קנ:ו    1          1

[2062 rows x 6 columns]

In [186]:
patterns = dict()
pattern_texts= dict()
spaces = [newline, space, s_space]
all_whitespace = r'(\\newline\\hspace\*\{\.5em\})|(\{\\hfill\})|(\\hspace\{1em\})'
perakim = re.split(perek_pattern,modfied_text)[1:]
for pi in range(len(perakim))[::2]:
    perek = perakim[pi]
    pesukim = re.split(passuk_pattern,perakim[pi+1])[1:]
    for vi in range(1,len(pesukim))[::2]:
        passuk = pesukim[vi-1]
        v_text = pesukim[vi]
        pattern = re.split(all_whitespace, v_text)
        if pattern:
            pattern = " ".join([p for p in pattern if p in spaces]).replace(newline, 'L').replace(space, 'T').replace(s_space, 'S')
            if patterns.get(pattern):
                patterns[pattern]+= 1
                pattern_texts[pattern].append(perek+":"+passuk)
            elif pattern:
                patterns[pattern] = 1
                pattern_texts[pattern] = [perek+":"+passuk]
        else:
            continue

In [187]:
patterns

{'T L T': 179,
 'T': 1893,
 'S T L': 156,
 'T T L': 14,
 'T T T': 103,
 'T T': 24,
 'T L': 26,
 'L T L': 1,
 'L S T L': 2,
 'L T': 32,
 'L T T L': 1,
 'T L T L T': 1,
 'L T L T': 4,
 'T S L': 32,
 'T L L T': 1,
 'L L T': 1,
 'T S T L L': 1,
 'T T L L': 2,
 'S T L T': 2,
 'S T L T L': 1,
 'T S L T': 1,
 'T S': 1,
 'S T': 1,
 'T T L S L': 1,
 'L': 4,
 'L T L L': 1,
 'L T T T': 1,
 'S T T L': 1}

In [200]:
pattern_texts['L']

['קל:א', 'קלט:א', 'קמב:א', 'קמו:א']

In [199]:
for p in patterns:
    for pt in pattern_texts[p]:
        per,pas = pt.split(':')
        if pas =="א" and p[0]!= 'L':
            print(pt, p,"\n",text_dict[pt])

א:א T L T
 ‏אַ֥שְֽׁרֵי הָאִ֗ישׁ	אֲשֶׁ֤ר | לֹ֥א הָלַךְ֮ בַּעֲצַ֢ת רְשָׁ֫עִ֥ים
וּבְדֶ֣רֶךְ חַ֭טָּאִים לֹ֥א עָמָ֑ד	וּבְמוֹשַׁ֥ב לֵ֝צִ֗ים לֹ֣א יָשָֽׁב׃

טו:א T L T
 ‏מִזְמ֗וֹר לְדָ֫וִ֥ד	יְ֭הֹוָה מִי־יָג֣וּר בְּאׇהֳלֶ֑ךָ
מִֽי־יִ֝שְׁכֹּ֗ן/ בְּהַ֣ר קׇדְשֶֽׁךָ׃

כו:א T L T
 ‏לְדָוִ֨ד | שׇׁפְטֵ֤נִי יְהֹוָ֗ה	כִּֽי־אֲ֭נִי בְּתֻמִּ֣י הָלַ֑כְתִּי
וּבַיהֹוָ֥ה בָּ֝טַ֗חְתִּי/ לֹ֣א אֶמְעָֽד׃

כז:א T L T
 ‏לְדָוִ֨ד | 	יְהֹוָ֤ה | אוֹרִ֣י וְ֭יִשְׁעִי מִמִּ֣י אִירָ֑א
יְהֹוָ֥ה מָעוֹז־חַ֝יַּ֗י/ מִמִּ֥י אֶפְחָֽד׃

כח:א T L T
 ‏לְדָוִ֡ד אֵ֘לֶ֤יךָ יְהֹוָ֨ה | אֶקְרָ֗א	צוּרִי֮ אַֽל־תֶּחֱרַ֢שׁ מִ֫מֶּ֥נִּי
פֶּן־תֶּחֱשֶׁ֥ה מִמֶּ֑נִּי	וְ֝נִמְשַׁ֗לְתִּי עִם־י֥וֹרְדֵי בֽוֹר׃

נו:א T L T
 ‏לַמְנַצֵּ֤חַ | עַל־י֬וֹנַת אֵ֣לֶם רְ֭חֹקִים	לְדָוִ֣ד מִכְתָּ֑ם
בֶּאֱחֹ֨ז אוֹת֖וֹ פְלִשְׁתִּ֣ים/ בְּגַֽת׃

קמד:א T L T
 ‏לְדָוִ֨ד | בָּ֘ר֤וּךְ יְהֹוָ֨ה | צוּרִ֗י	הַֽמְלַמֵּ֣ד יָדַ֣י לַקְרָ֑ב
אֶ֝צְבְּעוֹתַ֗י/ לַמִּלְחָמָֽה׃

ב:א T
 ‏לָ֭מָּה רָגְשׁ֣וּ גוֹיִ֑ם	וּ֝לְאֻמִּ֗ים יֶהְגּוּ־רִֽיק׃

ג:א T
 ‏מִזְמ֥וֹר לְדָוִ֑ד	בְּ֝בׇרְח֗וֹ מִפְּנֵ֤י | אַבְשָׁל֬וֹם בְּנֽוֹ׃

ה:א T
 ‏לַמְנַצֵּ֥חַ אֶֽל־הַנְּחִיל֗וֹת	מִזְמ֥וֹר לְדָוִֽד׃

ו:א T
 ‏לַמְנַצֵּ֣חַ בִּ֭נְגִינוֹת עַֽל־הַשְּׁמִינִ֗ית	מִזְמ֥וֹר לְדָוִֽד׃

ח:א T
 ‏לַמְנַצֵּ֥חַ עַֽל־הַגִּתִּ֗ית	מִזְמ֥וֹר לְדָוִֽד׃

ט:א T
 ‏לַ֭מְנַצֵּחַ עַל־מ֥וּת לַבֵּ֗ן	מִזְמ֥וֹר לְדָוִֽד׃

י:א T
 ‏לָמָ֣ה יְ֭הֹוָה תַּֽעֲמֹ֣ד בְּרָח֑וֹק	תַּ֝עְלִ֗ים לְעִתּ֥וֹת בַּצָּרָֽה׃

יב:א T
 ‏לַמְנַצֵּ֥חַ עַֽל־הַשְּׁמִינִ֗ית	מִזְמ֥וֹר לְדָוִֽד׃

כב:א T
 ‏לַ֭מְנַצֵּחַ עַל־אַיֶּ֥לֶת הַשַּׁ֗חַר	מִזְמ֥וֹר לְדָוִֽד׃

כג:א T
 ‏מִזְמ֥וֹר לְדָוִ֑ד	יְהֹוָ֥ה רֹ֝עִ֗י לֹ֣א אֶחְסָֽר׃

כה:א T
 ‏לְדָוִ֡ד	אֵלֶ֥יךָ יְ֝הֹוָ֗ה נַפְשִׁ֥י אֶשָּֽׂא׃

לג:א T
 ‏רַנְּנ֣וּ צַ֭דִּיקִים בַּֽיהֹוָ֑ה	לַ֝יְשָׁרִ֗ים נָאוָ֥ה תְהִלָּֽה׃

לז:א T
 ‏לְדָוִ֨ד | אַל־תִּתְחַ֥ר בַּמְּרֵעִ֑ים	אַל־תְּ֝קַנֵּ֗א בְּעֹשֵׂ֥י עַוְלָֽה׃

לט:א T
 ‏לַמְנַצֵּ֥חַ (לידיתון)\kri{לִֽידוּת֗וּן}	מִזְמ֥וֹר לְדָוִֽד׃

מו:א T
 ‏לַמְנַצֵּ֥חַ לִבְנֵי־קֹ֑רַח	עַֽל־עֲלָמ֥וֹת שִֽׁיר׃

נז:א T
 ‏לַמְנַצֵּ֣חַ אַל־תַּ֭שְׁחֵת לְדָוִ֣ד מִכְתָּ֑ם	בְּבׇרְח֥וֹ מִפְּנֵי־שָׁ֝א֗וּל בַּמְּעָרָֽה׃

ס:א T
 ‏לַ֭מְנַצֵּחַ עַל־שׁוּשַׁ֣ן עֵד֑וּת	מִכְתָּ֖ם לְדָוִ֣ד לְלַמֵּֽד׃

סב:א T
 ‏לַמְנַצֵּ֥חַ עַֽל־יְדוּת֗וּן	מִזְמ֥וֹר לְדָוִֽד׃

סג:א T
 ‏מִזְמ֥וֹר לְדָוִ֑ד	בִּ֝הְיוֹת֗וֹ בְּמִדְבַּ֥ר יְהוּדָֽה׃

סו:א T
 ‏לַ֭מְנַצֵּחַ שִׁ֣יר מִזְמ֑וֹר	הָרִ֥יעוּ לֵ֝אלֹהִ֗ים כׇּל־הָאָֽרֶץ׃

עא:א T
 ‏בְּךָֽ־יְהֹוָ֥ה חָסִ֑יתִי	אַל־אֵב֥וֹשָׁה לְעוֹלָֽם׃

פ:א T
 ‏לַמְנַצֵּ֥חַ אֶל־שֹׁשַׁנִּ֑ים	עֵד֖וּת לְאָסָ֣ף מִזְמֽוֹר׃

פז:א T
 ‏לִבְנֵי־קֹ֭רַח מִזְמ֣וֹר שִׁ֑יר	יְ֝סוּדָת֗וֹ בְּהַרְרֵי־קֹֽדֶשׁ׃

צא:א T
 ‏יֹ֭שֵׁב בְּסֵ֣תֶר עֶלְי֑וֹן	בְּצֵ֥ל שַׁ֝דַּ֗י יִתְלוֹנָֽן׃

צד:א T
 ‏אֵל־נְקָמ֥וֹת יְהֹוָ֑ה	אֵ֖ל נְקָמ֣וֹת הוֹפִֽיעַ׃

צה:א T
 ‏לְ֭כוּ נְרַנְּנָ֣ה לַיהֹוָ֑ה	נָ֝רִ֗יעָה לְצ֣וּר יִשְׁעֵֽנוּ׃

צו:א T
 ‏שִׁ֣ירוּ לַ֭יהֹוָה שִׁ֣יר חָדָ֑שׁ	שִׁ֥ירוּ לַ֝יהֹוָ֗ה כׇּל־הָאָֽרֶץ׃

צז:א T
 ‏יְהֹוָ֣ה מָ֭לָךְ תָּגֵ֣ל הָאָ֑רֶץ	יִ֝שְׂמְח֗וּ אִיִּ֥ים רַבִּֽים׃

צט:א T
 ‏יְהֹוָ֣ה מָ֭לָךְ יִרְגְּז֣וּ עַמִּ֑ים	יֹשֵׁ֥ב כְּ֝רוּבִ֗ים תָּנ֥וּט הָאָֽרֶץ׃

ק:א T
 ‏מִזְמ֥וֹר לְתוֹדָ֑ה	הָרִ֥יעוּ לַ֝יהֹוָ֗ה כׇּל־הָאָֽרֶץ׃

קב:א T
 ‏תְּ֭פִלָּה לְעָנִ֣י כִֽי־יַעֲטֹ֑ף	וְלִפְנֵ֥י יְ֝הֹוָ֗ה יִשְׁפֹּ֥ךְ שִׂיחֽוֹ׃

קג:א T
 ‏לְדָוִ֨ד | בָּרְכִ֣י נַ֭פְשִׁי אֶת־יְהֹוָ֑ה	וְכׇל־קְ֝רָבַ֗י אֶת־שֵׁ֥ם קׇדְשֽׁוֹ׃

קה:א T
 ‏הוֹד֣וּ לַ֭יהֹוָה קִרְא֣וּ בִשְׁמ֑וֹ	הוֹדִ֥יעוּ בָ֝עַמִּ֗ים עֲלִילוֹתָֽיו׃

קז:א T
 ‏הֹד֣וּ לַיהֹוָ֣ה כִּי־ט֑וֹב	כִּ֖י לְעוֹלָ֣ם חַסְדּֽוֹ׃

קיד:א T
 ‏בְּצֵ֣את יִ֭שְׂרָאֵל מִמִּצְרָ֑יִם	בֵּ֥ית יַ֝עֲקֹ֗ב מֵעַ֥ם לֹעֵֽז׃

קטז:א T
 ‏אָ֭הַבְתִּי כִּי־יִשְׁמַ֥ע | יְהֹוָ֑ה	אֶת־ק֝וֹלִ֗י תַּחֲנוּנָֽי׃

קיז:א T
 ‏הַֽלְל֣וּ אֶת־יְ֭הֹוָה כׇּל־גּוֹיִ֑ם	שַׁ֝בְּח֗וּהוּ כׇּל־הָאֻמִּֽים׃

קיח:א T
 ‏הוֹד֣וּ לַיהֹוָ֣ה כִּי־ט֑וֹב	כִּ֖י לְעוֹלָ֣ם חַסְדּֽוֹ׃

קיט:א T
 ‏אַשְׁרֵ֥י תְמִֽימֵי־דָ֑רֶךְ	הַ֝הֹלְכִ֗ים בְּתוֹרַ֥ת יְהֹוָֽה׃

קלו:א T
 ‏הוֹד֣וּ לַיהֹוָ֣ה כִּי־ט֑וֹב	כִּ֖י לְעוֹלָ֣ם חַסְדּֽוֹ׃

קלח:א T
 ‏לְדָוִ֨ד | אוֹדְךָ֥ בְכׇל־לִבִּ֑י	נֶ֖גֶד אֱלֹהִ֣ים אֲזַמְּרֶֽךָּ׃

מג:א S T L
 ‏שׇׁפְטֵ֤נִי אֱלֹהִ֨ים | / וְרִ֘יבָ֤ה רִיבִ֗י	מִגּ֥וֹי לֹֽא־חָסִ֑יד
מֵ֤אִישׁ מִרְמָ֖ה וְעַוְלָ֣ה תְפַלְּטֵֽנִי׃

צג:א S T L
 ‏יְהֹוָ֣ה מָלָךְ֮/ גֵּא֢וּת לָ֫בֵ֥שׁ	לָבֵ֣שׁ יְ֭הֹוָה עֹ֣ז הִתְאַזָּ֑ר
אַף־תִּכּ֥וֹן תֵּ֝בֵ֗ל בַּל־תִּמּֽוֹט׃

קד:א S T L
 ‏בָּרְכִ֥י נַפְשִׁ֗י/ אֶת־יְ֫הֹוָ֥ה	יְהֹוָ֣ה אֱ֭לֹהַי גָּדַ֣לְתָּ מְּאֹ֑ד
ה֖וֹד וְהָדָ֣ר לָבָֽשְׁתָּ׃

קטו:א S T L
 ‏לֹ֤א לָ֥נוּ יְהֹוָ֗ה/ לֹ֫א־לָ֥נוּ	כִּֽי־לְ֭שִׁמְךָ תֵּ֣ן כָּב֑וֹד
עַל־חַ֝סְדְּךָ֗ עַל־אֲמִתֶּֽךָ׃

צח:א T T L
 ‏מִזְמ֡וֹר	שִׁ֤ירוּ לַיהֹוָ֨ה | שִׁ֣יר חָ֭דָשׁ	כִּֽי־נִפְלָא֣וֹת עָשָׂ֑ה
הוֹשִׁיעָה־לּ֥וֹ יְ֝מִינ֗וֹ וּזְר֥וֹעַ קׇדְשֽׁוֹ׃

לב:א T T T
 ‏לְדָוִ֗ד מַ֫שְׂכִּ֥יל	אַשְׁרֵ֥י נְֽשׂוּי־פֶּ֗שַׁע	כְּס֣וּי/ חֲטָאָֽה׃

נט:א T T T
 ‏לַמְנַצֵּ֣חַ אַל־תַּשְׁחֵת֮ לְדָוִ֢ד מִ֫כְתָּ֥ם	בִּשְׁלֹ֥חַ שָׁא֑וּל	וַֽיִּשְׁמְר֥וּ אֶת־הַ֝בַּ֗יִת/ לַהֲמִיתֽוֹ׃

ז:א T L
 ‏שִׁגָּי֗וֹן לְדָ֫וִ֥ד	אֲשֶׁר־שָׁ֥ר לַֽיהֹוָ֑ה
עַל־דִּבְרֵי־כ֝֗וּשׁ בֶּן־יְמִינִֽי׃

כט:א T L
 ‏מִזְמ֗וֹר לְדָ֫וִ֥ד	הָב֣וּ לַ֭יהֹוָה בְּנֵ֣י אֵלִ֑ים
הָב֥וּ לַ֝יהֹוָ֗ה כָּב֥וֹד וָעֹֽז׃

לד:א T L
 ‏לְדָוִ֗ד	בְּשַׁנּוֹת֣וֹ אֶת־טַ֭עְמוֹ לִפְנֵ֣י אֲבִימֶ֑לֶךְ
וַ֝יְגָרְשֵׁ֗הוּ וַיֵּלַֽךְ׃

לה:א T L
 ‏לְדָוִ֨ד | 	רִיבָ֣ה יְ֭הֹוָה אֶת־יְרִיבַ֑י
לְ֝חַ֗ם אֶת־לֹחֲמָֽי׃

מה:א T L
 ‏לַמְנַצֵּ֣חַ עַל־שֹׁ֭שַׁנִּים	לִבְנֵי־קֹ֑רַח
מַ֝שְׂכִּ֗יל שִׁ֣יר יְדִידֹֽת׃

קא:א T L
 ‏לְדָוִ֗ד מִ֫זְמ֥וֹר	חֶֽסֶד־וּמִשְׁפָּ֥ט אָשִׁ֑ירָה
לְךָ֖ יְהֹוָ֣ה אֲזַמֵּֽרָה׃

עב:א T S L
 ‏לִשְׁלֹמֹ֨ה | 	אֱֽלֹהִ֗ים/ מִ֭שְׁפָּטֶיךָ לְמֶ֣לֶךְ תֵּ֑ן
וְצִדְקָתְךָ֥ לְבֶן־מֶֽלֶךְ׃

קלז:א T S L
 ‏עַ֥ל נַהֲר֨וֹת | בָּבֶ֗ל	שָׁ֣ם יָ֭שַׁבְנוּ/ גַּם־בָּכִ֑ינוּ
בְּ֝זׇכְרֵ֗נוּ אֶת־צִיּֽוֹן׃

Notes:
103 should have line break after L'David

In [167]:
all_whitespace

'(\\newline\\hspace*{.5em})|({\\hfill})|(\\hspace{1em})'

In [48]:
import re 
full_text = open('out/MAM-Psalms-tex_noNotes.tex').read().strip()
mod2=[]
perek_pattern = r'\\pstart\[\\subsection\*\{\\textcolor\{red\}\{פרק\s([א-ת]{1,3})\}\}\]'
passuk_pattern = r'\{\\loc\{ ([א-ת]{1,3})\}~\}‏'
newline= r'\newline\hspace*{.5em}'
space = r'{\hfill}'
s_space = "\\hspace{1em}"
spaces = [newline, space, s_space]
all_whitespace = r'(\\newline\\hspace\*\{\.5em\})|(\{\\hfill\})|(\\hspace\{1em\})'
perakim = re.split(perek_pattern,full_text)
mod2.append(perakim[0])
perakim = perakim[1:]
for pi in range(len(perakim))[::2]:
    perek = perakim[pi]
    pesukim = re.split(passuk_pattern,perakim[pi+1])[1:]
    mod2.append( '\\pstart[\\subsection*{\\textcolor{red}{פרק '+perek+'}}]')
    for vi in range(1,len(pesukim))[::2]:
        passuk = pesukim[vi-1]
        v_text = pesukim[vi]
        patterns = re.split(all_whitespace, v_text)
        if patterns:
            text = [s for s in patterns if s]
            patterns = [(p,i) for i,p in enumerate(text) if p in spaces]
            if passuk =="א":
                if len(patterns)>2:
                    for i,p in enumerate(patterns[1:]):
                        if i %2 ==1:
                            text[p[1]] = newline
                        else:
                            text[p[1]] = space
            else:
                if len(patterns)>1:
                    for i,p in enumerate(patterns):
                        if i %2 ==1:
                            text[p[1]] = newline
                        else:
                            text[p[1]] = space
            mod2.append('{\\loc{ '+passuk+'}~}‏'+"".join(text))
        else:
            mod2.append('{\\loc{ '+passuk+'}~}‏'+v_text)

In [52]:
len(mod2)

2678

In [50]:
with open('out/MAM-Psalms-tex_noNotes_mod2.tex', 'w') as f:
    f.write('\n'.join(mod2))

In [28]:
modfied_text = open('out/MAM-Psalms-tex_noNotes_mod2.tex').read().strip()
patterns = dict()
pattern_texts= dict()
spaces = [newline, space, s_space]
all_whitespace = r'(\\newline\\hspace\*\{\.5em\})|(\{\\hfill\})|(\\hspace\{1em\})'
perakim = re.split(perek_pattern,modfied_text)[1:]
for pi in range(len(perakim))[::2]:
    perek = perakim[pi]
    pesukim = re.split(passuk_pattern,perakim[pi+1])[1:]
    for vi in range(1,len(pesukim))[::2]:
        passuk = pesukim[vi-1]
        v_text = pesukim[vi]
        pattern = re.split(all_whitespace, v_text)
        if pattern:
            pattern = " ".join([p for p in pattern if p in spaces]).replace(newline, 'L').replace(space, 'T').replace(s_space, 'S')
            if patterns.get(pattern):
                patterns[pattern]+= 1
                pattern_texts[pattern].append(perek+":"+passuk)
            elif pattern:
                patterns[pattern] = 1
                pattern_texts[pattern] = [perek+":"+passuk]
        else:
            continue
patterns

{'T L T': 480,
 'T': 1892,
 'T L': 52,
 'L L T': 2,
 'L L T L': 9,
 'L T': 32,
 'T L T L T': 4,
 'T L T L': 7,
 'S L T': 4,
 'L': 5}

In [51]:
mod3=[]
def count_lines(text):
    return text.count(newline) + text.count("\\par")
modfied_text = open('out/MAM-Psalms-tex_noNotes_mod2.tex').read().strip()
perakim = re.split(perek_pattern,modfied_text)
mod3.append(perakim[0])
perakim = perakim[1:]
for pi in range(len(perakim))[::2]:
    mod3.append('\\pstart[\\subsection*{\\textcolor{red}{פרק '+perakim[pi]+'}}]')
    if len(perakim) < pi+2:
        count = count_lines(perakim[pi+1])
        next_count = count_lines(perakim[pi+2])
        if "\\ledpb" in perakim[pi+1] and count + next_count < 25:
            perakim[pi+1] = perakim[pi+1].replace("\\ledpb", "")
        elif "\\ledpb" not in perakim[pi+1] and count + next_count >= 25:
            perakim[pi+1] = perakim[pi+1]+"\\n\\ledpb"
    mod3.append(perakim[pi+1])
with open('out/MAM-Psalms-tex_noNotes_mod3.tex', 'w') as f:
    f.write(''.join(mod3))

In [33]:
line_count

[8,
 15,
 10,
 13,
 20,
 13,
 23,
 12,
 26,
 23,
 13,
 13,
 8,
 14,
 9,
 14,
 22,
 67,
 20,
 12,
 15,
 41,
 10,
 17,
 24,
 13,
 23,
 15,
 14,
 17,
 40,
 20,
 22,
 24,
 40,
 16,
 47,
 24,
 21,
 28,
 17,
 21,
 9,
 29,
 26,
 13,
 11,
 20,
 25,
 31,
 24,
 14,
 13,
 10,
 30,
 18,
 17,
 12,
 26,
 19,
 10,
 19,
 14,
 15,
 18,
 25,
 9,
 52,
 45,
 10,
 33,
 27,
 31,
 26,
 14,
 15,
 26,
 86,
 24,
 23,
 20,
 10,
 19,
 18,
 15,
 24,
 8,
 23,
 55,
 22,
 19,
 19,
 9,
 24,
 13,
 15,
 16,
 12,
 14,
 7,
 14,
 31,
 25,
 43,
 46,
 56,
 44,
 18,
 36,
 10,
 13,
 13,
 11,
 8,
 22,
 23,
 2,
 31,
 176,
 8,
 9,
 11,
 7,
 10,
 9,
 9,
 10,
 8,
 10,
 11,
 7,
 21,
 6,
 6,
 26,
 26,
 14,
 11,
 29,
 19,
 14,
 14,
 21,
 23,
 22,
 16,
 24,
 17,
 11,
 7]

In [38]:
joins = []
for p in range(len(line_count))[:-1]:
    if line_count[p] + line_count[p+1] < 25 and p-1 not in joins:
        joins.append(p)
        print(p+1, line_count[p], line_count[p+1])

1 8 15
3 10 13
12 13 8
14 14 9
46 13 11
53 13 10
99 14 7
110 10 13
112 13 11
120 8 9
122 11 7
124 10 9
126 9 10
128 8 10
130 11 7
133 6 6
149 11 7